// GENERATED by software/firmware/tools/gen_tables.js from software/face_v2 -- do not edit.

#include "spike_recipe.h"
#include "spike_moods.h"

namespace spike {

const char* const kSlotKeys[kNumSlots] = {"frame", "pattern", "muzzle", "eyeStyle", "eyeShape", "lashes", "brows", "nose", "mouth", "ears", "whiskers", "accessory", "freckles", "patternSide"};
static const char* const kOpt_frame[] = {"full", "head"};
static const char* const kOpt_pattern[] = {"plain", "patch", "spots", "tabby", "calico", "blaze", "mask", "tux"};
static const char* const kOpt_muzzle[] = {"none", "round", "wide"};
static const char* const kOpt_eyeStyle[] = {"gloss", "iris", "cat", "glow"};
static const char* const kOpt_eyeShape[] = {"oval", "round", "almond", "soft", "droop"};
static const char* const kOpt_lashes[] = {"none", "flick", "full"};
static const char* const kOpt_brows[] = {"none", "dots", "arcs", "bold"};
static const char* const kOpt_nose[] = {"pup", "button", "cat", "heart", "bean"};
static const char* const kOpt_mouth[] = {"pup", "omega", "simple"};
static const char* const kOpt_ears[] = {"floppy", "pointy", "round", "bear", "bunny", "fold", "none"};
static const char* const kOpt_whiskers[] = {"none", "short", "long"};
static const char* const kOpt_accessory[] = {"none", "bow", "bandana", "glasses", "hat", "flower"};
static const char* const kOpt_freckles[] = {"no", "yes"};
static const char* const kOpt_patternSide[] = {"left", "right"};
const char* const* const kSlotOptions[kNumSlots] = {kOpt_frame, kOpt_pattern, kOpt_muzzle, kOpt_eyeStyle, kOpt_eyeShape, kOpt_lashes, kOpt_brows, kOpt_nose, kOpt_mouth, kOpt_ears, kOpt_whiskers, kOpt_accessory, kOpt_freckles, kOpt_patternSide};
const uint8_t kSlotOptionCount[kNumSlots] = {2, 8, 3, 4, 5, 3, 4, 5, 3, 7, 3, 6, 2, 2};
const char* const kColorKeys[kNumColors] = {"bg", "fur", "fur2", "fur3", "muzzleColor", "eyeColor", "irisColor", "noseColor", "lineColor", "tongueColor", "earColor", "earInner", "blushColor", "browColor", "whiskerColor", "accColor"};
const char* const kNumberKeys[kNumNumbers] = {"eyeSize", "eyeSpacing", "mouthRest", "blush", "dim"};
const float kNumberRange[kNumNumbers][2] = {{0.8f, 1.25f}, {0.86f, 1.14f}, {0.0f, 0.6f}, {0.0f, 0.8f}, {0.0f, 0.6f}};

const PresetDef kPresets[] = {
  {"classic", false, {"Classic Pup", 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xBFE3F2, 0xF3DDBF, 0xC98A5E, 0x8A5A3C, 0xFFF4E4, 0x2E2320, 0x7A4B2A, 0x2E2320, 0x4A2E24, 0xE0564F, 0xC98A5E, 0xB07650, 0xFF8C8C, 0xA8714D, 0x8A6A55, 0xE84A5F, 1.0f, 1.0f, 0.55f, 0.22f, 0.0f}, "SPK1-01000000000000-giwa0-BFE3F2F3DDBFC98A5E8A5A3CFFF4E42E23207A4B2A2E23204A2E24E0564FC98A5EB07650FF8C8CA8714D8A6A55E84A5F"},
  {"spicy", true, {"Spicy", 0, 4, 0, 2, 2, 1, 0, 2, 1, 1, 2, 1, 0, 0, 0xBFE3F2, 0xFBF3E8, 0xE8964A, 0x4A3B36, 0xFFF4E4, 0x2A2226, 0x8CCB5E, 0xF28CA0, 0x5A3A3A, 0xE0564F, 0xE8964A, 0xF6B3C0, 0xFF8C8C, 0xA8714D, 0x9A8A80, 0xFF5C9A, 1.05f, 1.0f, 0.05f, 0.3f, 0.0f}, "SPK1-04022102112100-ji3d0-BFE3F2FBF3E8E8964A4A3B36FFF4E42A22268CCB5EF28CA05A3A3AE0564FE8964AF6B3C0FF8C8CA8714D9A8A80FF5C9A"},
  {"beagle", false, {"Beagle", 0, 5, 0, 0, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0xBFE3F2, 0xC8874E, 0xFFF7EE, 0x8A5A3C, 0xFFF4E4, 0x2E2320, 0x7A4B2A, 0x2A201C, 0x3A2A22, 0xE0564F, 0x6E4326, 0x5A361E, 0xFF8C8C, 0xA8714D, 0x8A6A55, 0xE84A5F, 1.0f, 1.0f, 0.55f, 0.15f, 0.0f}, "SPK1-05004004000000-giw70-BFE3F2C8874EFFF7EE8A5A3CFFF4E42E23207A4B2A2A201C3A2A22E0564F6E43265A361EFF8C8CA8714D8A6A55E84A5F"},
  {"husky", false, {"Husky", 0, 6, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0xBFE3F2, 0xF4F6F8, 0x6B7280, 0x8A5A3C, 0xFFF4E4, 0x1F2430, 0x6EC6F2, 0x1F2430, 0x2E3440, 0xE0564F, 0x6B7280, 0xF2C4C4, 0xFF8C8C, 0xA8714D, 0x8A6A55, 0xE84A5F, 1.02f, 1.0f, 0.55f, 0.18f, 0.0f}, "SPK1-06012000010000-hiw80-BFE3F2F4F6F86B72808A5A3CFFF4E41F24306EC6F21F24302E3440E0564F6B7280F2C4C4FF8C8CA8714D8A6A55E84A5F"},
  {"minimal", false, {"Minimal", 0, 0, 0, 3, 3, 0, 0, 1, 2, 6, 0, 0, 0, 0, 0xBFE3F2, 0x0E1117, 0xC98A5E, 0x8A5A3C, 0xFFF4E4, 0xFFFFFF, 0x7A4B2A, 0xD8DEE9, 0xFFFFFF, 0xFF7A8A, 0xC98A5E, 0xB07650, 0xFF6B8A, 0xA8714D, 0x8A6A55, 0xE84A5F, 1.0f, 1.0f, 0.25f, 0.28f, 0.0f}, "SPK1-00033001260000-gifc0-BFE3F20E1117C98A5E8A5A3CFFF4E4FFFFFF7A4B2AD8DEE9FFFFFFFF7A8AC98A5EB07650FF6B8AA8714D8A6A55E84A5F"},
  {"night", false, {"Night", 0, 0, 0, 3, 3, 0, 0, 1, 2, 6, 0, 0, 0, 0, 0xBFE3F2, 0x0B0D14, 0xC98A5E, 0x8A5A3C, 0xFFF4E4, 0xFFB86B, 0x7A4B2A, 0x9A7654, 0xFFB86B, 0xC8645A, 0xC98A5E, 0xB07650, 0xC86A5A, 0xA8714D, 0x8A6A55, 0xE84A5F, 1.0f, 1.0f, 0.15f, 0.2f, 0.35f}, "SPK1-00033001260000-gi99k-BFE3F20B0D14C98A5E8A5A3CFFF4E4FFB86B7A4B2A9A7654FFB86BC8645AC98A5EB07650C86A5AA8714D8A6A55E84A5F"},
  {"anime", false, {"Anime Pup", 0, 1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0xBFE3F2, 0xF6E4CB, 0xC98A5E, 0x8A5A3C, 0xFFF4E4, 0x3A2A24, 0x8B5A3C, 0x2E2320, 0x4A2E24, 0xE0564F, 0xC98A5E, 0xB07650, 0xFF8C8C, 0x6B4430, 0x8A6A55, 0xE84A5F, 1.1f, 1.0f, 0.4f, 0.4f, 0.0f}, "SPK1-01010021000000-nini0-BFE3F2F6E4CBC98A5E8A5A3CFFF4E43A2A248B5A3C2E23204A2E24E0564FC98A5EB07650FF8C8C6B44308A6A55E84A5F"},
  {"sticker", false, {"Sticker Buddy", 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0xBFE3F2, 0xF3DDBF, 0xC98A5E, 0x8A5A3C, 0xFFF7EE, 0x2E2320, 0x7A4B2A, 0x2E2320, 0x4A2E24, 0xE0564F, 0xC98A5E, 0xB07650, 0xFF8C8C, 0xB98159, 0x8A6A55, 0xE84A5F, 0.86f, 1.08f, 0.25f, 0.45f, 0.0f}, "SPK1-11101011100000-5sfk0-BFE3F2F3DDBFC98A5E8A5A3CFFF7EE2E23207A4B2A2E23204A2E24E0564FC98A5EB07650FF8C8CB981598A6A55E84A5F"},
  {"tuxedo", true, {"Midnight Tux", 0, 7, 0, 2, 1, 2, 0, 2, 1, 1, 2, 0, 0, 0, 0xBFE3F2, 0x2F2C38, 0xF4F0EC, 0x8A5A3C, 0xFFF4E4, 0x15121A, 0xD4E157, 0xF59AB0, 0x3A2E36, 0xE0564F, 0x2F2C38, 0xF2A3B8, 0xFF7FA8, 0xF4F0EC, 0xF4F0EC, 0xE84A5F, 1.12f, 1.0f, 0.05f, 0.35f, 0.0f}, "SPK1-07021202112000-pi3f0-BFE3F22F2C38F4F0EC8A5A3CFFF4E415121AD4E157F59AB03A2E36E0564F2F2C38F2A3B8FF7FA8F4F0ECF4F0ECE84A5F"},
};
const int kNumPresets = 9;

static const FieldValue kDog_neutral[] = {{F_smile, 0.4f}, {F_tongue, 0.4f}};
static const FieldValue kCat_neutral[] = {{F_smile, 0.4f}, {F_tongue, 0.12f}, {F_lidTL, 0.12f}, {F_lidTR, 0.12f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_pant, 0.0f}};
static const FieldValue kDog_happy[] = {{F_smile, 0.85f}, {F_open, 0.3f}, {F_tongue, 0.45f}, {F_lidBL, 0.14f}, {F_lidBR, 0.14f}, {F_lidBulge, 0.5f}, {F_sparkle, 0.35f}, {F_blush, 0.3f}, {F_earPerk, 0.45f}, {F_browY, 0.35f}, {F_bob, -2.0f}};
static const FieldValue kCat_happy[] = {{F_smile, 0.7f}, {F_open, 0.08f}, {F_tongue, 0.135f}, {F_lidBL, 0.16f}, {F_lidBR, 0.16f}, {F_lidBulge, 0.55f}, {F_sparkle, 0.35f}, {F_blush, 0.3f}, {F_earPerk, 0.45f}, {F_browY, 0.35f}, {F_bob, -2.0f}, {F_lidTL, 0.54f}, {F_lidTR, 0.54f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_pant, 0.0f}};
static const MotionDef kMot_happy[] = {{F_tilt, 2.0f, 0.45f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_excited[] = {{F_smile, 1.0f}, {F_open, 0.7f}, {F_tongue, 0.8f}, {F_pant, 0.7f}, {F_eyeScale, 1.1f}, {F_pupil, 1.3f}, {F_sparkle, 0.8f}, {F_shine, 1.2f}, {F_earPerk, 1.1f}, {F_browY, 0.8f}, {F_headSY, 1.05f}, {F_headSX, 0.97f}, {F_bob, -4.0f}, {F_blush, 0.3f}};
static const FieldValue kCat_excited[] = {{F_smile, 1.0f}, {F_open, 0.7f}, {F_tongue, 0.8f}, {F_pant, 0.0f}, {F_eyeScale, 1.1f}, {F_pupil, 1.625f}, {F_sparkle, 0.8f}, {F_shine, 1.2f}, {F_earPerk, 1.1f}, {F_browY, 0.8f}, {F_headSY, 1.05f}, {F_headSX, 0.97f}, {F_bob, -4.0f}, {F_blush, 0.3f}};
static const MotionDef kMot_excited[] = {{F_bob, -4.0f, 3.2f, MOTION_HOP, 0.0f}, {F_earL, 6.0f, 3.2f, MOTION_SIN, 0.0f}, {F_earR, 6.0f, 3.2f, MOTION_SIN, 1.2f}, {F_headSY, 0.025f, 3.2f, MOTION_SIN, 0.0f}};
static const ExtraEnter kEnter_excited[] = {{Particle::Sparkle, 240.0f, 60.0f, 5}};
static const FieldValue kDog_love[] = {{F_iconAmt, 1.0f}, {F_smile, 0.85f}, {F_open, 0.28f}, {F_tongue, 0.4f}, {F_blush, 0.85f}, {F_tilt, 5.0f}, {F_earPerk, 0.3f}, {F_browY, 0.3f}};
static const FieldValue kCat_love[] = {{F_iconAmt, 1.0f}, {F_smile, 0.85f}, {F_open, 0.28f}, {F_tongue, 0.12f}, {F_blush, 0.85f}, {F_tilt, 5.0f}, {F_earPerk, 0.3f}, {F_browY, 0.3f}, {F_pupil, 1.25f}, {F_pant, 0.0f}};
static const MotionDef kMot_love[] = {{F_tilt, 3.0f, 0.5f, MOTION_SIN, 0.0f}, {F_bob, 1.2f, 1.1f, MOTION_SIN, 0.0f}, {F_iconAmt, 0.06f, 1.6f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_laughing[] = {{F_happy, 1.0f}, {F_smile, 1.1f}, {F_open, 0.85f}, {F_tongue, 0.5f}, {F_tear, 0.25f}, {F_blush, 0.5f}, {F_earPerk, 0.6f}, {F_headSX, 1.04f}, {F_headSY, 0.97f}, {F_browY, 0.6f}};
static const FieldValue kCat_laughing[] = {{F_happy, 1.0f}, {F_smile, 1.1f}, {F_open, 0.85f}, {F_tongue, 0.15f}, {F_tear, 0.25f}, {F_blush, 0.5f}, {F_earPerk, 0.6f}, {F_headSX, 1.04f}, {F_headSY, 0.97f}, {F_browY, 0.6f}, {F_pupil, 1.25f}, {F_pant, 0.0f}};
static const MotionDef kMot_laughing[] = {{F_bob, -3.0f, 5.5f, MOTION_HOP, 0.0f}, {F_tilt, 3.0f, 1.8f, MOTION_SIN, 0.0f}, {F_open, 0.12f, 5.5f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_playful[] = {{F_wink, -1.0f}, {F_smile, 0.9f}, {F_open, 0.45f}, {F_tongue, 0.85f}, {F_skew, 0.3f}, {F_earPerk, 0.5f}, {F_tilt, -7.0f}, {F_browY, 0.35f}, {F_blush, 0.25f}, {F_sparkle, 0.3f}};
static const FieldValue kCat_playful[] = {{F_wink, -1.0f}, {F_smile, 0.7f}, {F_open, 0.3f}, {F_tongue, 0.9f}, {F_skew, 0.6799999999999999f}, {F_earPerk, 0.5f}, {F_tilt, -7.0f}, {F_browY, 0.35f}, {F_blush, 0.25f}, {F_sparkle, 0.3f}, {F_lidTL, 0.12f}, {F_lidTR, 0.12f}, {F_pupil, 0.5f}, {F_pant, 0.0f}};
static const MotionDef kMot_playful[] = {{F_tilt, 4.0f, 0.9f, MOTION_SIN, 0.0f}, {F_earR, 8.0f, 1.8f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_curious[] = {{F_tilt, 13.0f}, {F_eyeScaleR, 1.14f}, {F_eyeScaleL, 0.97f}, {F_browY, 0.6f}, {F_smile, 0.2f}, {F_mouthO, 0.4f}, {F_open, 0.2f}, {F_earPerk, 0.7f}, {F_earL, -10.0f}, {F_pupil, 1.15f}};
static const FieldValue kCat_curious[] = {{F_tilt, 13.0f}, {F_eyeScaleR, 1.14f}, {F_eyeScaleL, 0.97f}, {F_browY, 0.6f}, {F_smile, 0.2f}, {F_mouthO, 0.4f}, {F_open, 0.2f}, {F_earPerk, 0.7f}, {F_earL, -10.0f}, {F_pupil, 1.4375f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_curious[] = {{F_tilt, 2.5f, 0.4f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_sad[] = {{F_smile, -0.6f}, {F_lidTL, 0.2f}, {F_lidTR, 0.2f}, {F_lidTilt, -0.75f}, {F_eyeDY, 3.0f}, {F_eyeScale, 1.05f}, {F_pupil, 1.25f}, {F_shine, 1.3f}, {F_tear, 0.5f}, {F_earPerk, -1.0f}, {F_browY, 0.25f}, {F_browTilt, -0.9f}, {F_tilt, -4.0f}, {F_mouthW, 0.8f}, {F_wobble, 0.3f}};
static const FieldValue kCat_sad[] = {{F_smile, -0.6f}, {F_lidTL, 0.32f}, {F_lidTR, 0.32f}, {F_lidTilt, -0.75f}, {F_eyeDY, 3.0f}, {F_eyeScale, 1.05f}, {F_pupil, 0.625f}, {F_shine, 1.3f}, {F_tear, 0.5f}, {F_earPerk, -1.0f}, {F_browY, 0.25f}, {F_browTilt, -0.9f}, {F_tilt, -4.0f}, {F_mouthW, 0.8f}, {F_wobble, 0.3f}, {F_skew, 0.18f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_sad[] = {{F_bob, 1.0f, 0.3f, MOTION_SIN, 0.0f}, {F_wobble, 0.15f, 0.6f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_caring[] = {{F_smile, 0.5f}, {F_lidTL, 0.16f}, {F_lidTR, 0.16f}, {F_lidBulge, 0.35f}, {F_lidBL, 0.1f}, {F_lidBR, 0.1f}, {F_lidTilt, -0.3f}, {F_pupil, 1.2f}, {F_shine, 1.15f}, {F_tilt, 6.0f}, {F_blush, 0.35f}, {F_browTilt, -0.4f}, {F_browY, 0.2f}, {F_earPerk, -0.2f}};
static const FieldValue kCat_caring[] = {{F_smile, 0.5f}, {F_lidTL, 0.28f}, {F_lidTR, 0.28f}, {F_lidBulge, 0.35f}, {F_lidBL, 0.1f}, {F_lidBR, 0.1f}, {F_lidTilt, -0.3f}, {F_pupil, 0.6f}, {F_shine, 1.15f}, {F_tilt, 6.0f}, {F_blush, 0.35f}, {F_browTilt, -0.4f}, {F_browY, 0.2f}, {F_earPerk, -0.2f}, {F_skew, 0.18f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_caring[] = {{F_tilt, 2.5f, 0.35f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_sleepy[] = {{F_lidTL, 0.56f}, {F_lidTR, 0.56f}, {F_lidSag, 0.45f}, {F_smile, 0.12f}, {F_eyeDY, 2.0f}, {F_earPerk, -0.7f}, {F_tilt, 6.0f}, {F_bob, 2.0f}, {F_mouthW, 0.82f}, {F_browY, -0.2f}};
static const FieldValue kCat_sleepy[] = {{F_lidTL, 0.68f}, {F_lidTR, 0.68f}, {F_lidSag, 0.45f}, {F_smile, 0.12f}, {F_eyeDY, 2.0f}, {F_earPerk, -0.7f}, {F_tilt, 6.0f}, {F_bob, 2.0f}, {F_mouthW, 0.82f}, {F_browY, -0.2f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_sleepy[] = {{F_lidTL, 0.1f, 0.22f, MOTION_SIN, 0.0f}, {F_lidTR, 0.1f, 0.22f, MOTION_SIN, 0.0f}, {F_tilt, 3.0f, 0.15f, MOTION_SIN, 0.0f}, {F_bob, 2.0f, 0.15f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_sleeping[] = {{F_shut, 1.0f}, {F_smile, 0.12f}, {F_bubble, 1.0f}, {F_earPerk, -0.9f}, {F_tilt, 8.0f}, {F_bob, 3.0f}, {F_dim, 0.12f}, {F_mouthW, 0.8f}, {F_browY, -0.3f}};
static const FieldValue kCat_sleeping[] = {{F_shut, 1.0f}, {F_smile, 0.12f}, {F_bubble, 1.0f}, {F_earPerk, -0.9f}, {F_tilt, 8.0f}, {F_bob, 3.0f}, {F_dim, 0.12f}, {F_mouthW, 0.8f}, {F_browY, -0.3f}, {F_lidTL, 0.12f}, {F_lidTR, 0.12f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_sleeping[] = {{F_bob, 2.2f, 0.22f, MOTION_SIN, 0.0f}, {F_earL, 3.0f, 0.22f, MOTION_SIN, 0.0f}, {F_headSY, 0.012f, 0.22f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_bored[] = {{F_lidTL, 0.42f}, {F_lidTR, 0.42f}, {F_lidTilt, 0.1f}, {F_smile, -0.05f}, {F_lookX, 0.55f}, {F_lookY, -0.35f}, {F_tilt, -4.0f}, {F_earPerk, -0.5f}, {F_mouthW, 0.8f}, {F_skew, -0.3f}};
static const FieldValue kCat_bored[] = {{F_lidTL, 0.54f}, {F_lidTR, 0.54f}, {F_lidTilt, 0.1f}, {F_smile, -0.05f}, {F_lookX, 0.55f}, {F_lookY, -0.35f}, {F_tilt, -4.0f}, {F_earPerk, -0.5f}, {F_mouthW, 0.8f}, {F_skew, -0.12f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_bored[] = {{F_lidTL, 0.08f, 0.2f, MOTION_SIN, 0.0f}, {F_lidTR, 0.08f, 0.2f, MOTION_SIN, 0.0f}, {F_lookX, 0.2f, 0.12f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_sulking[] = {{F_lidTL, 0.3f}, {F_lidTR, 0.3f}, {F_lidTilt, 0.25f}, {F_smile, -0.45f}, {F_mouthW, 0.62f}, {F_skew, -0.2f}, {F_lookX, -0.7f}, {F_lookY, 0.25f}, {F_tilt, -8.0f}, {F_earPerk, -0.8f}, {F_blush, 0.35f}, {F_browTilt, 0.4f}};
static const FieldValue kCat_sulking[] = {{F_lidTL, 0.62f}, {F_lidTR, 0.62f}, {F_lidTilt, 0.25f}, {F_smile, -0.45f}, {F_mouthW, 0.62f}, {F_skew, -0.020000000000000018f}, {F_lookX, -0.95f}, {F_lookY, 0.25f}, {F_tilt, -10.0f}, {F_earPerk, -0.8f}, {F_blush, 0.35f}, {F_browTilt, 0.4f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_sulking[] = {{F_lookX, 0.12f, 0.15f, MOTION_SIN, 0.0f}, {F_tilt, 1.5f, 0.2f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_scared[] = {{F_eyeScale, 1.18f}, {F_pupil, 0.55f}, {F_shine, 0.85f}, {F_lidBL, 0.08f}, {F_lidBR, 0.08f}, {F_lidTilt, -0.45f}, {F_mouthO, 0.5f}, {F_open, 0.4f}, {F_smile, -0.4f}, {F_wobble, 0.7f}, {F_earBack, 1.0f}, {F_earPerk, -0.5f}, {F_sweat, 1.0f}, {F_browTilt, -0.9f}, {F_browY, 0.8f}, {F_headSX, 0.95f}, {F_headSY, 1.03f}, {F_gloom, 0.3f}};
static const FieldValue kCat_scared[] = {{F_eyeScale, 1.18f}, {F_pupil, 0.6875f}, {F_shine, 0.85f}, {F_lidBL, 0.08f}, {F_lidBR, 0.08f}, {F_lidTilt, -0.45f}, {F_mouthO, 0.5f}, {F_open, 0.4f}, {F_smile, -0.4f}, {F_wobble, 0.7f}, {F_earBack, 1.2f}, {F_earPerk, -0.5f}, {F_sweat, 1.0f}, {F_browTilt, -0.9f}, {F_browY, 0.8f}, {F_headSX, 0.95f}, {F_headSY, 1.03f}, {F_gloom, 0.3f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_scared[] = {{F_shakeX, 1.6f, 11.0f, MOTION_JITTER, 0.0f}, {F_tilt, 1.2f, 9.0f, MOTION_JITTER, 1.0f}};
static const ExtraEnter kEnter_scared[] = {{Particle::Exclaim, 300.0f, 38.0f, 1}};
static const FieldValue kDog_surprised[] = {{F_eyeScale, 1.16f}, {F_eyeSY, 1.07f}, {F_pupil, 0.85f}, {F_mouthO, 1.0f}, {F_open, 0.6f}, {F_smile, 0.1f}, {F_browY, 1.1f}, {F_earPerk, 1.1f}, {F_shine, 1.1f}, {F_headSY, 1.04f}};
static const FieldValue kCat_surprised[] = {{F_eyeScale, 1.16f}, {F_eyeSY, 1.07f}, {F_pupil, 1.0625f}, {F_mouthO, 1.0f}, {F_open, 0.6f}, {F_smile, 0.1f}, {F_browY, 1.1f}, {F_earPerk, 1.1f}, {F_shine, 1.1f}, {F_headSY, 1.04f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const ExtraEnter kEnter_surprised[] = {{Particle::Exclaim, 240.0f, 38.0f, 1}};
static const FieldValue kDog_cuteAngry[] = {{F_lidTL, 0.15f}, {F_lidTR, 0.15f}, {F_lidTilt, 0.6f}, {F_smile, -0.35f}, {F_open, 0.32f}, {F_mouthW, 0.55f}, {F_fang, 1.0f}, {F_blush, 0.65f}, {F_vein, 0.8f}, {F_browTilt, 0.8f}, {F_earBack, 0.4f}, {F_headSX, 1.05f}, {F_headSY, 0.96f}, {F_eyeScale, 1.05f}};
static const FieldValue kCat_cuteAngry[] = {{F_lidTL, 0.15f}, {F_lidTR, 0.15f}, {F_lidTilt, 0.8f}, {F_smile, -0.4f}, {F_open, 0.65f}, {F_mouthW, 0.7f}, {F_fang, 1.0f}, {F_blush, 0.65f}, {F_vein, 0.8f}, {F_browTilt, 0.8f}, {F_earBack, 1.2f}, {F_headSX, 1.05f}, {F_headSY, 0.96f}, {F_eyeScale, 1.05f}, {F_pupil, 1.25f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_cuteAngry[] = {{F_bob, -2.5f, 3.0f, MOTION_HOP, 0.0f}, {F_shakeX, 0.8f, 9.0f, MOTION_JITTER, 0.0f}};
static const FieldValue kDog_dizzy[] = {{F_iconAmt, 1.0f}, {F_smile, -0.1f}, {F_open, 0.35f}, {F_tongue, 0.75f}, {F_mouthW, 0.8f}, {F_skew, 0.35f}, {F_earPerk, -0.3f}};
static const FieldValue kCat_dizzy[] = {{F_iconAmt, 1.0f}, {F_smile, -0.1f}, {F_open, 0.35f}, {F_tongue, 0.75f}, {F_mouthW, 0.8f}, {F_skew, 0.35f}, {F_earPerk, -0.3f}, {F_pupil, 1.25f}, {F_pant, 0.0f}};
static const MotionDef kMot_dizzy[] = {{F_tilt, 12.0f, 0.8f, MOTION_SIN, 0.0f}, {F_bob, 2.0f, 1.6f, MOTION_SIN, 0.0f}, {F_lookX, 0.4f, 0.8f, MOTION_SIN, 0.0f}};
static const ExtraEnter kEnter_dizzy[] = {{Particle::DizzyStar, 240.0f, 40.0f, 3}};
static const FieldValue kDog_proud[] = {{F_happy, 1.0f}, {F_smile, 0.8f}, {F_open, 0.2f}, {F_tongue, 0.3f}, {F_tilt, -5.0f}, {F_bob, -3.0f}, {F_headSY, 1.04f}, {F_earPerk, 0.7f}, {F_browY, 0.5f}, {F_blush, 0.2f}};
static const FieldValue kCat_proud[] = {{F_happy, 1.0f}, {F_smile, 0.8f}, {F_open, 0.2f}, {F_tongue, 0.09f}, {F_tilt, -5.0f}, {F_bob, -3.0f}, {F_headSY, 1.04f}, {F_earPerk, 0.7f}, {F_browY, 0.5f}, {F_blush, 0.2f}, {F_lidTL, 0.12f}, {F_lidTR, 0.12f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_pant, 0.0f}};
static const MotionDef kMot_proud[] = {{F_bob, -1.0f, 0.6f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_embarrassed[] = {{F_lidTL, 0.15f}, {F_lidTR, 0.15f}, {F_lidTilt, -0.4f}, {F_smile, 0.25f}, {F_wobble, 0.35f}, {F_mouthW, 0.7f}, {F_blush, 1.0f}, {F_blushLines, 1.0f}, {F_sweat, 0.8f}, {F_lookX, -0.5f}, {F_lookY, 0.4f}, {F_tilt, 6.0f}, {F_earPerk, -0.4f}, {F_browTilt, -0.6f}};
static const FieldValue kCat_embarrassed[] = {{F_lidTL, 0.27f}, {F_lidTR, 0.27f}, {F_lidTilt, -0.4f}, {F_smile, 0.25f}, {F_wobble, 0.35f}, {F_mouthW, 0.7f}, {F_blush, 1.0f}, {F_blushLines, 1.0f}, {F_sweat, 0.8f}, {F_lookX, -0.5f}, {F_lookY, 0.4f}, {F_tilt, 6.0f}, {F_earPerk, -0.4f}, {F_browTilt, -0.6f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_embarrassed[] = {{F_lookX, 0.15f, 0.5f, MOTION_SIN, 0.0f}, {F_tilt, 2.0f, 0.6f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_begging[] = {{F_eyeScale, 1.14f}, {F_pupil, 1.55f}, {F_shine, 1.5f}, {F_sparkle, 0.6f}, {F_tear, 0.35f}, {F_lidTilt, -0.55f}, {F_lidTL, 0.05f}, {F_lidTR, 0.05f}, {F_smile, 0.1f}, {F_mouthO, 0.3f}, {F_open, 0.15f}, {F_tilt, -9.0f}, {F_earPerk, -0.6f}, {F_browTilt, -1.0f}, {F_browY, 0.7f}, {F_headSY, 1.02f}};
static const FieldValue kCat_begging[] = {{F_eyeScale, 1.14f}, {F_pupil, 1.9375f}, {F_shine, 1.5f}, {F_sparkle, 0.6f}, {F_tear, 0.35f}, {F_lidTilt, -0.55f}, {F_lidTL, 0.05f}, {F_lidTR, 0.05f}, {F_smile, 0.1f}, {F_mouthO, 0.3f}, {F_open, 0.15f}, {F_tilt, -9.0f}, {F_earPerk, -0.6f}, {F_browTilt, -1.0f}, {F_browY, 0.7f}, {F_headSY, 1.02f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_begging[] = {{F_tilt, 3.0f, 0.45f, MOTION_SIN, 0.0f}, {F_bob, 1.2f, 0.9f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_cuddly[] = {{F_lidTL, 0.5f}, {F_lidTR, 0.5f}, {F_lidSag, 0.3f}, {F_lidBulge, 0.5f}, {F_lidBL, 0.2f}, {F_lidBR, 0.2f}, {F_smile, 0.7f}, {F_blush, 0.6f}, {F_tilt, 7.0f}, {F_earPerk, -0.3f}, {F_bob, 2.0f}};
static const FieldValue kCat_cuddly[] = {{F_lidTL, 0.62f}, {F_lidTR, 0.62f}, {F_lidSag, 0.3f}, {F_lidBulge, 0.5f}, {F_lidBL, 0.2f}, {F_lidBR, 0.2f}, {F_smile, 0.7f}, {F_blush, 0.6f}, {F_tilt, 7.0f}, {F_earPerk, -0.3f}, {F_bob, 2.0f}, {F_shut, 0.9f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_cuddly[] = {{F_tilt, 2.5f, 0.25f, MOTION_SIN, 0.0f}, {F_bob, 1.5f, 0.25f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_wakeupAlarm[] = {{F_eyeScale, 1.15f}, {F_pupil, 1.1f}, {F_sparkle, 0.5f}, {F_smile, 0.85f}, {F_open, 0.75f}, {F_tongue, 0.6f}, {F_earPerk, 1.2f}, {F_browY, 1.0f}, {F_headSY, 1.06f}, {F_bob, -3.0f}};
static const FieldValue kCat_wakeupAlarm[] = {{F_eyeScale, 1.15f}, {F_pupil, 1.375f}, {F_sparkle, 0.5f}, {F_smile, 0.85f}, {F_open, 0.75f}, {F_tongue, 0.18f}, {F_earPerk, 1.2f}, {F_browY, 1.0f}, {F_headSY, 1.06f}, {F_bob, -3.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_wakeupAlarm[] = {{F_bob, -5.0f, 3.6f, MOTION_HOP, 0.0f}, {F_tilt, 5.0f, 1.8f, MOTION_SIN, 0.0f}, {F_earL, 10.0f, 3.6f, MOTION_SIN, 0.0f}, {F_earR, 10.0f, 3.6f, MOTION_SIN, 1.5f}};
static const FieldValue kDog_joy[] = {{F_happy, 1.0f}, {F_smile, 1.0f}, {F_open, 0.55f}, {F_tongue, 0.55f}, {F_blush, 0.45f}, {F_earPerk, 0.7f}, {F_browY, 0.5f}, {F_bob, -3.0f}, {F_headSY, 1.03f}};
static const FieldValue kCat_joy[] = {{F_happy, 1.0f}, {F_smile, 1.0f}, {F_open, 0.55f}, {F_tongue, 0.165f}, {F_blush, 0.45f}, {F_earPerk, 0.7f}, {F_browY, 0.5f}, {F_bob, -3.0f}, {F_headSY, 1.03f}, {F_pupil, 1.25f}, {F_pant, 0.0f}};
static const MotionDef kMot_joy[] = {{F_bob, -3.5f, 2.2f, MOTION_HOP, 0.0f}, {F_tilt, 3.0f, 1.1f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_delight[] = {{F_iconAmt, 1.0f}, {F_smile, 0.95f}, {F_open, 0.45f}, {F_tongue, 0.5f}, {F_blush, 0.4f}, {F_earPerk, 0.8f}, {F_browY, 0.7f}, {F_headSY, 1.03f}};
static const FieldValue kCat_delight[] = {{F_iconAmt, 1.0f}, {F_smile, 0.95f}, {F_open, 0.45f}, {F_tongue, 0.15f}, {F_blush, 0.4f}, {F_earPerk, 0.8f}, {F_browY, 0.7f}, {F_headSY, 1.03f}, {F_pupil, 1.25f}, {F_pant, 0.0f}};
static const MotionDef kMot_delight[] = {{F_bob, -2.5f, 2.6f, MOTION_HOP, 0.0f}, {F_iconAmt, 0.08f, 2.6f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_anger[] = {{F_lidTL, 0.18f}, {F_lidTR, 0.18f}, {F_lidTilt, 0.85f}, {F_lidBL, 0.1f}, {F_lidBR, 0.1f}, {F_smile, -0.5f}, {F_open, 0.28f}, {F_mouthW, 0.62f}, {F_fang, 0.8f}, {F_vein, 1.0f}, {F_browTilt, 1.0f}, {F_browY, -0.6f}, {F_earBack, 0.85f}, {F_eyeScale, 0.96f}, {F_headSX, 1.03f}, {F_headSY, 0.98f}, {F_scrunch, 0.35f}};
static const FieldValue kCat_anger[] = {{F_lidTL, 0.18f}, {F_lidTR, 0.18f}, {F_lidTilt, 0.85f}, {F_lidBL, 0.1f}, {F_lidBR, 0.1f}, {F_smile, -0.5f}, {F_open, 0.55f}, {F_mouthW, 0.62f}, {F_fang, 0.8f}, {F_vein, 1.0f}, {F_browTilt, 1.0f}, {F_browY, -0.6f}, {F_earBack, 1.2f}, {F_eyeScale, 0.96f}, {F_headSX, 1.03f}, {F_headSY, 0.98f}, {F_scrunch, 0.35f}, {F_pupil, 1.25f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_anger[] = {{F_shakeX, 1.0f, 8.0f, MOTION_JITTER, 0.0f}, {F_tilt, 1.2f, 7.0f, MOTION_JITTER, 2.0f}};
static const FieldValue kDog_frustration[] = {{F_lidTL, 0.3f}, {F_lidTR, 0.3f}, {F_lidTilt, 0.5f}, {F_smile, -0.4f}, {F_wobble, 0.45f}, {F_open, 0.12f}, {F_mouthW, 0.8f}, {F_scrunch, 0.45f}, {F_vein, 0.5f}, {F_earBack, 0.5f}, {F_browTilt, 0.7f}};
static const FieldValue kCat_frustration[] = {{F_lidTL, 0.42f}, {F_lidTR, 0.42f}, {F_lidTilt, 0.5f}, {F_smile, -0.4f}, {F_wobble, 0.45f}, {F_open, 0.12f}, {F_mouthW, 0.8f}, {F_scrunch, 0.45f}, {F_vein, 0.5f}, {F_earBack, 0.6f}, {F_browTilt, 0.7f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_frustration[] = {{F_tilt, 4.0f, 1.5f, MOTION_SIN, 0.0f}, {F_shakeX, 1.5f, 1.5f, MOTION_SIN, 1.57f}};
static const FieldValue kDog_disgust[] = {{F_lidTL, 0.35f}, {F_lidTR, 0.28f}, {F_lidTilt, 0.2f}, {F_lidBL, 0.25f}, {F_lidBR, 0.25f}, {F_smile, -0.5f}, {F_skew, -0.5f}, {F_open, 0.3f}, {F_tongue, 0.75f}, {F_mouthW, 0.7f}, {F_scrunch, 1.0f}, {F_gloom, 0.6f}, {F_tilt, -8.0f}, {F_lookX, 0.55f}, {F_earBack, 0.4f}, {F_browTilt, 0.5f}};
static const FieldValue kCat_disgust[] = {{F_lidTL, 0.47f}, {F_lidTR, 0.4f}, {F_lidTilt, 0.2f}, {F_lidBL, 0.25f}, {F_lidBR, 0.25f}, {F_smile, -0.5f}, {F_skew, -0.32f}, {F_open, 0.3f}, {F_tongue, 0.75f}, {F_mouthW, 0.7f}, {F_scrunch, 1.0f}, {F_gloom, 0.6f}, {F_tilt, -8.0f}, {F_lookX, 0.55f}, {F_earBack, 0.48f}, {F_browTilt, 0.5f}, {F_pupil, 0.5f}, {F_pant, 0.0f}};
static const MotionDef kMot_disgust[] = {{F_tilt, 2.0f, 0.6f, MOTION_SIN, 0.0f}, {F_scrunch, 0.1f, 1.5f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_grief[] = {{F_lidTL, 0.3f}, {F_lidTR, 0.3f}, {F_lidTilt, -0.9f}, {F_tear, 0.9f}, {F_cry, 1.0f}, {F_smile, -0.8f}, {F_open, 0.3f}, {F_mouthW, 0.7f}, {F_wobble, 0.6f}, {F_earPerk, -1.2f}, {F_tilt, -5.0f}, {F_bob, 4.0f}, {F_gloom, 0.8f}, {F_browTilt, -1.0f}, {F_eyeDY, 4.0f}, {F_shine, 1.2f}};
static const FieldValue kCat_grief[] = {{F_lidTL, 0.42f}, {F_lidTR, 0.42f}, {F_lidTilt, -0.9f}, {F_tear, 0.9f}, {F_cry, 1.0f}, {F_smile, -0.8f}, {F_open, 0.3f}, {F_mouthW, 0.7f}, {F_wobble, 0.6f}, {F_earPerk, -1.2f}, {F_tilt, -5.0f}, {F_bob, 4.0f}, {F_gloom, 0.8f}, {F_browTilt, -1.0f}, {F_eyeDY, 4.0f}, {F_shine, 1.2f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_grief[] = {{F_bob, 2.5f, 1.6f, MOTION_JITTER, 0.0f}, {F_wobble, 0.2f, 1.0f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_loneliness[] = {{F_lidTL, 0.25f}, {F_lidTR, 0.25f}, {F_lidTilt, -0.6f}, {F_tear, 0.4f}, {F_smile, -0.35f}, {F_mouthW, 0.7f}, {F_lookX, -0.6f}, {F_lookY, 0.5f}, {F_tilt, -6.0f}, {F_earPerk, -1.0f}, {F_gloom, 0.3f}, {F_pupil, 1.2f}, {F_browTilt, -0.7f}};
static const FieldValue kCat_loneliness[] = {{F_lidTL, 0.37f}, {F_lidTR, 0.37f}, {F_lidTilt, -0.6f}, {F_tear, 0.4f}, {F_smile, -0.35f}, {F_mouthW, 0.7f}, {F_lookX, -0.6f}, {F_lookY, 0.5f}, {F_tilt, -6.0f}, {F_earPerk, -1.0f}, {F_gloom, 0.3f}, {F_pupil, 0.6f}, {F_browTilt, -0.7f}, {F_skew, 0.18f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_loneliness[] = {{F_lookY, 0.08f, 0.2f, MOTION_SIN, 0.0f}, {F_tilt, 1.5f, 0.2f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_hope[] = {{F_eyeScale, 1.08f}, {F_pupil, 1.35f}, {F_shine, 1.35f}, {F_sparkle, 0.6f}, {F_lidTilt, -0.3f}, {F_smile, 0.35f}, {F_mouthO, 0.25f}, {F_open, 0.15f}, {F_lookY, -0.55f}, {F_tilt, 5.0f}, {F_earPerk, 0.5f}, {F_browY, 0.6f}, {F_browTilt, -0.4f}};
static const FieldValue kCat_hope[] = {{F_eyeScale, 1.08f}, {F_pupil, 1.6875f}, {F_shine, 1.35f}, {F_sparkle, 0.6f}, {F_lidTilt, -0.3f}, {F_smile, 0.35f}, {F_mouthO, 0.25f}, {F_open, 0.15f}, {F_lookY, -0.55f}, {F_tilt, 5.0f}, {F_earPerk, 0.5f}, {F_browY, 0.6f}, {F_browTilt, -0.4f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_hope[] = {{F_tilt, 2.0f, 0.5f, MOTION_SIN, 0.0f}, {F_bob, -1.5f, 0.5f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_shyness[] = {{F_lidTL, 0.25f}, {F_lidTR, 0.25f}, {F_lidBulge, 0.4f}, {F_lidBL, 0.12f}, {F_lidBR, 0.12f}, {F_smile, 0.35f}, {F_mouthW, 0.6f}, {F_blush, 0.9f}, {F_blushLines, 0.6f}, {F_lookX, -0.6f}, {F_lookY, 0.45f}, {F_tilt, 7.0f}, {F_earPerk, -0.5f}, {F_browTilt, -0.4f}};
static const FieldValue kCat_shyness[] = {{F_lidTL, 0.37f}, {F_lidTR, 0.37f}, {F_lidBulge, 0.4f}, {F_lidBL, 0.12f}, {F_lidBR, 0.12f}, {F_smile, 0.35f}, {F_mouthW, 0.6f}, {F_blush, 0.9f}, {F_blushLines, 0.6f}, {F_lookX, -0.6f}, {F_lookY, 0.45f}, {F_tilt, 7.0f}, {F_earPerk, -0.5f}, {F_browTilt, -0.4f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_shyness[] = {{F_lookX, 0.2f, 0.35f, MOTION_SIN, 1.0f}, {F_tilt, 2.0f, 0.35f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_jealousy[] = {{F_lidTL, 0.4f}, {F_lidTR, 0.4f}, {F_lidTilt, 0.35f}, {F_smile, -0.35f}, {F_skew, -0.4f}, {F_mouthW, 0.7f}, {F_lookX, -0.85f}, {F_tilt, -6.0f}, {F_earBack, 0.3f}, {F_browTilt, 0.5f}, {F_blush, 0.2f}};
static const FieldValue kCat_jealousy[] = {{F_lidTL, 0.52f}, {F_lidTR, 0.52f}, {F_lidTilt, 0.35f}, {F_smile, -0.35f}, {F_skew, -0.22000000000000003f}, {F_mouthW, 0.7f}, {F_lookX, -0.85f}, {F_tilt, -6.0f}, {F_earBack, 0.36f}, {F_browTilt, 0.5f}, {F_blush, 0.2f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_jealousy[] = {{F_lookX, 0.12f, 0.8f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_confusion[] = {{F_tilt, 15.0f}, {F_eyeScaleL, 1.12f}, {F_eyeScaleR, 0.9f}, {F_lidTR, 0.22f}, {F_smile, -0.1f}, {F_skew, -0.4f}, {F_mouthW, 0.7f}, {F_earL, -14.0f}, {F_earR, 8.0f}, {F_browY, 0.4f}};
static const FieldValue kCat_confusion[] = {{F_tilt, 15.0f}, {F_eyeScaleL, 1.12f}, {F_eyeScaleR, 0.9f}, {F_lidTR, 0.33999999999999997f}, {F_smile, -0.1f}, {F_skew, -0.22000000000000003f}, {F_mouthW, 0.7f}, {F_earL, -14.0f}, {F_earR, 8.0f}, {F_browY, 0.4f}, {F_lidTL, 0.12f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_confusion[] = {{F_tilt, 6.0f, 0.5f, MOTION_SIN, 0.0f}};
static const ExtraEnter kEnter_confusion[] = {{Particle::Question, 300.0f, 40.0f, 1}};
static const FieldValue kDog_suspicion[] = {{F_lidTL, 0.45f}, {F_lidTR, 0.3f}, {F_lidTilt, 0.35f}, {F_lidBL, 0.2f}, {F_lidBR, 0.2f}, {F_smile, -0.1f}, {F_skew, 0.35f}, {F_mouthW, 0.6f}, {F_lookX, 0.6f}, {F_tilt, -4.0f}, {F_earBack, 0.2f}, {F_browTilt, 0.3f}};
static const FieldValue kCat_suspicion[] = {{F_lidTL, 0.5700000000000001f}, {F_lidTR, 0.42f}, {F_lidTilt, 0.35f}, {F_lidBL, 0.2f}, {F_lidBR, 0.2f}, {F_smile, -0.1f}, {F_skew, 0.53f}, {F_mouthW, 0.6f}, {F_lookX, 0.6f}, {F_tilt, -4.0f}, {F_earBack, 0.24f}, {F_browTilt, 0.3f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_suspicion[] = {{F_lookX, 0.25f, 0.18f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_relief[] = {{F_shut, 0.85f}, {F_smile, 0.55f}, {F_open, 0.2f}, {F_mouthO, 0.3f}, {F_tilt, -3.0f}, {F_earPerk, -0.2f}, {F_bob, 2.0f}, {F_blush, 0.2f}, {F_sweat, 0.5f}};
static const FieldValue kCat_relief[] = {{F_shut, 0.85f}, {F_smile, 0.55f}, {F_open, 0.2f}, {F_mouthO, 0.3f}, {F_tilt, -3.0f}, {F_earPerk, -0.2f}, {F_bob, 2.0f}, {F_blush, 0.2f}, {F_sweat, 0.5f}, {F_lidTL, 0.12f}, {F_lidTR, 0.12f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_relief[] = {{F_bob, 1.5f, 0.4f, MOTION_SIN, 0.0f}, {F_headSY, 0.02f, 0.4f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_gratitude[] = {{F_happy, 1.0f}, {F_smile, 0.8f}, {F_open, 0.2f}, {F_tongue, 0.3f}, {F_blush, 0.5f}, {F_tilt, 4.0f}, {F_earPerk, 0.2f}, {F_tear, 0.3f}};
static const FieldValue kCat_gratitude[] = {{F_happy, 1.0f}, {F_smile, 0.8f}, {F_open, 0.2f}, {F_tongue, 0.09f}, {F_blush, 0.5f}, {F_tilt, 4.0f}, {F_earPerk, 0.2f}, {F_tear, 0.3f}, {F_lidTL, 0.12f}, {F_lidTR, 0.12f}, {F_skew, 0.18f}, {F_pupil, 0.5f}, {F_pant, 0.0f}};
static const MotionDef kMot_gratitude[] = {{F_tilt, 3.0f, 0.7f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_mischief[] = {{F_lidTL, 0.3f}, {F_lidTR, 0.3f}, {F_lidTilt, 0.35f}, {F_lidBulge, 0.5f}, {F_lidBL, 0.15f}, {F_lidBR, 0.15f}, {F_smile, 0.7f}, {F_skew, 0.6f}, {F_fang, 1.0f}, {F_lookX, 0.45f}, {F_tilt, 6.0f}, {F_earPerk, 0.4f}, {F_browTilt, 0.5f}, {F_blush, 0.2f}};
static const FieldValue kCat_mischief[] = {{F_lidTL, 0.42f}, {F_lidTR, 0.42f}, {F_lidTilt, 0.35f}, {F_lidBulge, 0.5f}, {F_lidBL, 0.15f}, {F_lidBR, 0.15f}, {F_smile, 0.7f}, {F_skew, 0.98f}, {F_fang, 1.0f}, {F_lookX, 0.45f}, {F_tilt, 6.0f}, {F_earPerk, 0.4f}, {F_browTilt, 0.5f}, {F_blush, 0.2f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_mischief[] = {{F_skew, 0.12f, 1.2f, MOTION_SIN, 0.0f}, {F_tilt, 2.0f, 0.6f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_determination[] = {{F_lidTL, 0.18f}, {F_lidTR, 0.18f}, {F_lidTilt, 0.45f}, {F_smile, 0.1f}, {F_mouthW, 0.8f}, {F_earPerk, 0.8f}, {F_browTilt, 0.6f}, {F_browY, -0.3f}, {F_sparkle, 0.6f}, {F_headSY, 1.03f}, {F_pupil, 1.1f}};
static const FieldValue kCat_determination[] = {{F_lidTL, 0.3f}, {F_lidTR, 0.3f}, {F_lidTilt, 0.45f}, {F_smile, 0.1f}, {F_mouthW, 0.8f}, {F_earPerk, 0.8f}, {F_browTilt, 0.6f}, {F_browY, -0.3f}, {F_sparkle, 0.6f}, {F_headSY, 1.03f}, {F_pupil, 0.55f}, {F_skew, 0.18f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_determination[] = {{F_bob, 0.8f, 2.5f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_nervousness[] = {{F_lidTilt, -0.4f}, {F_eyeScale, 1.05f}, {F_pupil, 0.8f}, {F_smile, 0.1f}, {F_wobble, 0.7f}, {F_mouthW, 0.8f}, {F_sweat, 1.0f}, {F_blush, 0.2f}, {F_lookX, 0.3f}, {F_earBack, 0.5f}, {F_browTilt, -0.7f}};
static const FieldValue kCat_nervousness[] = {{F_lidTilt, -0.4f}, {F_eyeScale, 1.05f}, {F_pupil, 0.4f}, {F_smile, 0.1f}, {F_wobble, 0.7f}, {F_mouthW, 0.8f}, {F_sweat, 1.0f}, {F_blush, 0.2f}, {F_lookX, 0.3f}, {F_earBack, 0.6f}, {F_browTilt, -0.7f}, {F_lidTL, 0.12f}, {F_lidTR, 0.12f}, {F_skew, 0.18f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_nervousness[] = {{F_shakeX, 1.2f, 10.0f, MOTION_JITTER, 0.0f}, {F_lookX, 0.35f, 0.9f, MOTION_SIN, 0.0f}, {F_bob, 0.8f, 11.0f, MOTION_JITTER, 2.0f}};
static const FieldValue kDog_awe[] = {{F_eyeScale, 1.2f}, {F_pupil, 1.5f}, {F_shine, 1.4f}, {F_sparkle, 1.0f}, {F_mouthO, 0.9f}, {F_open, 0.5f}, {F_smile, 0.2f}, {F_browY, 1.0f}, {F_earPerk, 0.8f}, {F_lookY, -0.4f}, {F_headSY, 1.03f}};
static const FieldValue kCat_awe[] = {{F_eyeScale, 1.2f}, {F_pupil, 1.875f}, {F_shine, 1.4f}, {F_sparkle, 1.0f}, {F_mouthO, 0.9f}, {F_open, 0.5f}, {F_smile, 0.2f}, {F_browY, 1.0f}, {F_earPerk, 0.8f}, {F_lookY, -0.4f}, {F_headSY, 1.03f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_awe[] = {{F_headSY, 0.02f, 0.3f, MOTION_SIN, 0.0f}, {F_sparkle, 0.2f, 1.3f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_smugness[] = {{F_lidTL, 0.42f}, {F_lidTR, 0.42f}, {F_lidBulge, 0.4f}, {F_lidBL, 0.12f}, {F_lidBR, 0.12f}, {F_smile, 0.55f}, {F_skew, 0.55f}, {F_mouthW, 0.8f}, {F_tilt, -6.0f}, {F_earPerk, 0.3f}, {F_browTilt, 0.2f}, {F_browY, 0.3f}};
static const FieldValue kCat_smugness[] = {{F_lidTL, 0.67f}, {F_lidTR, 0.67f}, {F_lidBulge, 0.4f}, {F_lidBL, 0.12f}, {F_lidBR, 0.12f}, {F_smile, 0.55f}, {F_skew, 0.8799999999999999f}, {F_mouthW, 0.8f}, {F_tilt, -6.0f}, {F_earPerk, 0.3f}, {F_browTilt, 0.2f}, {F_browY, 0.3f}, {F_pupil, 0.5f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_smugness[] = {{F_tilt, 2.0f, 0.4f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_silliness[] = {{F_eyeScaleL, 1.15f}, {F_eyeScaleR, 0.85f}, {F_cross, 0.6f}, {F_smile, 0.9f}, {F_open, 0.6f}, {F_tongue, 1.0f}, {F_skew, 0.4f}, {F_tilt, 10.0f}, {F_earPerk, 0.6f}, {F_headSX, 1.05f}};
static const FieldValue kCat_silliness[] = {{F_eyeScaleL, 1.15f}, {F_eyeScaleR, 0.85f}, {F_cross, 0.6f}, {F_smile, 0.9f}, {F_open, 0.6f}, {F_tongue, 1.0f}, {F_skew, 0.5800000000000001f}, {F_tilt, 10.0f}, {F_earPerk, 0.6f}, {F_headSX, 1.05f}, {F_lidTL, 0.12f}, {F_lidTR, 0.12f}, {F_pupil, 0.5f}, {F_pant, 0.0f}};
static const MotionDef kMot_silliness[] = {{F_tilt, 7.0f, 2.2f, MOTION_SIN, 0.0f}, {F_cross, 0.2f, 1.1f, MOTION_SIN, 0.0f}};
static const FieldValue kDog_hungry[] = {{F_batt, 1.0f}, {F_lick, 1.0f}, {F_eyeScale, 1.14f}, {F_pupil, 1.55f}, {F_shine, 1.5f}, {F_sparkle, 0.45f}, {F_tear, 0.45f}, {F_lidTilt, -0.55f}, {F_lidTL, 0.04f}, {F_lidTR, 0.04f}, {F_browTilt, -1.0f}, {F_browY, 0.7f}, {F_smile, 0.05f}, {F_open, 0.12f}, {F_mouthW, 0.8f}, {F_tilt, -7.0f}, {F_earPerk, -0.6f}, {F_headSY, 1.02f}};
static const FieldValue kCat_hungry[] = {{F_batt, 1.0f}, {F_lick, 1.0f}, {F_eyeScale, 1.14f}, {F_pupil, 1.9375f}, {F_shine, 1.5f}, {F_sparkle, 0.45f}, {F_tear, 0.45f}, {F_lidTilt, -0.55f}, {F_lidTL, 0.04f}, {F_lidTR, 0.04f}, {F_browTilt, -1.0f}, {F_browY, 0.7f}, {F_smile, 0.05f}, {F_open, 0.12f}, {F_mouthW, 0.8f}, {F_tilt, -7.0f}, {F_earPerk, -0.6f}, {F_headSY, 1.02f}, {F_tongue, 0.0f}, {F_pant, 0.0f}};
static const MotionDef kMot_hungry[] = {{F_shakeX, 1.8f, 13.0f, MOTION_RUMBLE, 0.0f}, {F_headSY, 0.03f, 13.0f, MOTION_RUMBLE, 1.3f}, {F_bob, 1.2f, 13.0f, MOTION_RUMBLE, 0.6f}, {F_tilt, 2.5f, 0.35f, MOTION_SIN, 0.0f}};

const MoodDef kMoods[] = {
  {"neutral", "Neutral", kDog_neutral, 2, Icon::None, kCat_neutral, 7, Icon::None, nullptr, 0, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"happy", "Happy", kDog_happy, 11, Icon::None, kCat_happy, 16, Icon::None, kMot_happy, 1, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"excited", "Excited", kDog_excited, 14, Icon::None, kCat_excited, 14, Icon::None, kMot_excited, 4, {kEnter_excited, 1, true, 1.0f, Particle::Sparkle, 240.0f, 50.0f, 170.0f}, true},
  {"love", "Love", kDog_love, 8, Icon::Heart, kCat_love, 10, Icon::Heart, kMot_love, 3, {nullptr, 0, true, 1.1f, Particle::Heart, 240.0f, 70.0f, 150.0f}, true},
  {"laughing", "Laughing", kDog_laughing, 10, Icon::None, kCat_laughing, 12, Icon::None, kMot_laughing, 3, {nullptr, 0, true, 1.4f, Particle::Sparkle, 240.0f, 60.0f, 170.0f}, true},
  {"playful", "Playful", kDog_playful, 10, Icon::None, kCat_playful, 14, Icon::None, kMot_playful, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"curious", "Curious", kDog_curious, 10, Icon::None, kCat_curious, 12, Icon::None, kMot_curious, 1, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"sad", "Sad", kDog_sad, 15, Icon::None, kCat_sad, 18, Icon::None, kMot_sad, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"caring", "Caring", kDog_caring, 14, Icon::None, kCat_caring, 17, Icon::None, kMot_caring, 1, {nullptr, 0, true, 3.0f, Particle::Heart, 240.0f, 80.0f, 130.0f}, true},
  {"sleepy", "Sleepy", kDog_sleepy, 10, Icon::None, kCat_sleepy, 14, Icon::None, kMot_sleepy, 4, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"sleeping", "Sleeping", kDog_sleeping, 9, Icon::None, kCat_sleeping, 15, Icon::None, kMot_sleeping, 3, {nullptr, 0, true, 1.8f, Particle::Zzz, 330.0f, 70.0f, 0.0f}, false},
  {"bored", "Bored", kDog_bored, 10, Icon::None, kCat_bored, 13, Icon::None, kMot_bored, 3, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"sulking", "Sulking", kDog_sulking, 12, Icon::None, kCat_sulking, 15, Icon::None, kMot_sulking, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"scared", "Scared", kDog_scared, 18, Icon::None, kCat_scared, 20, Icon::None, kMot_scared, 2, {kEnter_scared, 1, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"surprised", "Surprised", kDog_surprised, 10, Icon::None, kCat_surprised, 12, Icon::None, nullptr, 0, {kEnter_surprised, 1, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"cuteAngry", "Cute-angry", kDog_cuteAngry, 14, Icon::None, kCat_cuteAngry, 17, Icon::None, kMot_cuteAngry, 2, {nullptr, 0, true, 1.9f, Particle::Steam, 240.0f, 36.0f, 170.0f}, true},
  {"dizzy", "Dizzy", kDog_dizzy, 7, Icon::Spiral, kCat_dizzy, 9, Icon::Spiral, kMot_dizzy, 3, {kEnter_dizzy, 1, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"proud", "Proud", kDog_proud, 10, Icon::None, kCat_proud, 15, Icon::None, kMot_proud, 1, {nullptr, 0, true, 1.3f, Particle::Sparkle, 240.0f, 40.0f, 170.0f}, true},
  {"embarrassed", "Embarrassed", kDog_embarrassed, 14, Icon::None, kCat_embarrassed, 18, Icon::None, kMot_embarrassed, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"begging", "Begging", kDog_begging, 16, Icon::None, kCat_begging, 18, Icon::None, kMot_begging, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"cuddly", "Cuddly", kDog_cuddly, 11, Icon::None, kCat_cuddly, 16, Icon::None, kMot_cuddly, 2, {nullptr, 0, true, 2.4f, Particle::Heart, 240.0f, 80.0f, 130.0f}, true},
  {"wakeupAlarm", "Wake-up alarm", kDog_wakeupAlarm, 10, Icon::None, kCat_wakeupAlarm, 11, Icon::None, kMot_wakeupAlarm, 4, {nullptr, 0, true, 0.7f, Particle::Exclaim, 240.0f, 40.0f, 180.0f}, true},
  {"joy", "Joy", kDog_joy, 9, Icon::None, kCat_joy, 11, Icon::None, kMot_joy, 2, {nullptr, 0, true, 0.9f, Particle::Sparkle, 240.0f, 60.0f, 190.0f}, true},
  {"delight", "Delight", kDog_delight, 8, Icon::Star, kCat_delight, 10, Icon::Star, kMot_delight, 2, {nullptr, 0, true, 0.8f, Particle::Sparkle, 240.0f, 60.0f, 190.0f}, true},
  {"anger", "Anger", kDog_anger, 17, Icon::None, kCat_anger, 20, Icon::None, kMot_anger, 2, {nullptr, 0, true, 1.6f, Particle::Steam, 240.0f, 36.0f, 170.0f}, true},
  {"frustration", "Frustration", kDog_frustration, 11, Icon::None, kCat_frustration, 15, Icon::None, kMot_frustration, 2, {nullptr, 0, true, 2.2f, Particle::Steam, 240.0f, 36.0f, 170.0f}, true},
  {"disgust", "Disgust", kDog_disgust, 16, Icon::None, kCat_disgust, 18, Icon::None, kMot_disgust, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"grief", "Grief", kDog_grief, 16, Icon::None, kCat_grief, 20, Icon::None, kMot_grief, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"loneliness", "Lonely", kDog_loneliness, 13, Icon::None, kCat_loneliness, 16, Icon::None, kMot_loneliness, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"hope", "Hope", kDog_hope, 13, Icon::None, kCat_hope, 15, Icon::None, kMot_hope, 2, {nullptr, 0, true, 2.0f, Particle::Sparkle, 240.0f, 40.0f, 130.0f}, false},
  {"shyness", "Shy", kDog_shyness, 14, Icon::None, kCat_shyness, 18, Icon::None, kMot_shyness, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"jealousy", "Jealous", kDog_jealousy, 11, Icon::None, kCat_jealousy, 14, Icon::None, kMot_jealousy, 1, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"confusion", "Confused", kDog_confusion, 10, Icon::None, kCat_confusion, 14, Icon::None, kMot_confusion, 1, {kEnter_confusion, 1, true, 2.6f, Particle::Question, 300.0f, 40.0f, 30.0f}, true},
  {"suspicion", "Suspicious", kDog_suspicion, 12, Icon::None, kCat_suspicion, 15, Icon::None, kMot_suspicion, 1, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"relief", "Relief", kDog_relief, 9, Icon::None, kCat_relief, 15, Icon::None, kMot_relief, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"gratitude", "Grateful", kDog_gratitude, 8, Icon::None, kCat_gratitude, 13, Icon::None, kMot_gratitude, 1, {nullptr, 0, true, 1.8f, Particle::Heart, 240.0f, 80.0f, 150.0f}, true},
  {"mischief", "Mischief", kDog_mischief, 14, Icon::None, kCat_mischief, 17, Icon::None, kMot_mischief, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"determination", "Determined", kDog_determination, 11, Icon::None, kCat_determination, 14, Icon::None, kMot_determination, 1, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"nervousness", "Nervous", kDog_nervousness, 11, Icon::None, kCat_nervousness, 16, Icon::None, kMot_nervousness, 3, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"awe", "Awe", kDog_awe, 11, Icon::None, kCat_awe, 13, Icon::None, kMot_awe, 2, {nullptr, 0, true, 1.2f, Particle::Sparkle, 240.0f, 50.0f, 190.0f}, true},
  {"smugness", "Smug", kDog_smugness, 12, Icon::None, kCat_smugness, 15, Icon::None, kMot_smugness, 1, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
  {"silliness", "Silly", kDog_silliness, 10, Icon::None, kCat_silliness, 14, Icon::None, kMot_silliness, 2, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, false},
  {"hungry", "Hungry (low battery)", kDog_hungry, 18, Icon::None, kCat_hungry, 20, Icon::None, kMot_hungry, 4, {nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}, true},
};
const int kNumMoods = 43;

}  // namespace spike
