/*
 * gen_tables.js -- generates the C++ data tables of lib/spike_face from face_v2 itself, so the firmware
 * never re-types a number:
 *   lib/spike_face/src/spike_fields.inc      params.js: field, default, range, spring [k, d]
 *   lib/spike_face/src/spike_tables_gen.cpp  recipe.js slots/colours/numbers/presets (+ share codes),
 *                                            moods.js faces (dog, and cat with catify applied), motion,
 *                                            extras, followsLook
 * It only READS face_v2 (require). Run after any face_v2 table change:
 *   node software/firmware/tools/gen_tables.js
 */
'use strict';
var path = require('path'), fs = require('fs');
var FACE = path.join(__dirname, '..', '..', 'face_v2');
function req(f) { return require(path.join(FACE, f)); }
var FP = req('params.js');
var Recipe = req('recipe.js');
var Moods = req('moods.js');

var OUT = path.join(__dirname, '..', 'lib', 'spike_face', 'src');

function num(v) {
  if (typeof v !== 'number' || !isFinite(v)) throw new Error('bad number ' + v);
  var s = String(v);
  if (s.indexOf('.') < 0 && s.indexOf('e') < 0) s += '.0';
  return s + 'f';
}
function hex(c) { return '0x' + c.replace('#', '').toUpperCase(); }
function cstr(s) { return JSON.stringify(String(s)); }

var header = '// GENERATED by software/firmware/tools/gen_tables.js from software/face_v2 -- do not edit.\n';

// ---------------------------------------------------------------------------------------- fields
var lines = [header, '// X(name, default, lo, hi, spring_k, spring_d)', '#define SPIKE_FIELDS(X) \\'];
FP.FIELDS.forEach(function (f, i) {
  var r = FP.RANGES[f], tn = FP.TUNE[FP.GROUP[f] || 'shape'];
  lines.push('  X(' + [f, num(FP.DEFAULTS[f]), num(r[0]), num(r[1]), num(tn[0]), num(tn[1])].join(', ') + ')' +
    (i < FP.FIELDS.length - 1 ? ' \\' : ''));
});
fs.writeFileSync(path.join(OUT, 'spike_fields.inc'), lines.join('\n') + '\n');

// ---------------------------------------------------------------------------------------- tables
var o = [header, '#include "spike_recipe.h"', '#include "spike_moods.h"', '', 'namespace spike {', ''];
var SLOT_KEYS = Object.keys(Recipe.SLOTS);
var NUM_KEYS = Object.keys(Recipe.NUMBERS);

o.push('const char* const kSlotKeys[kNumSlots] = {' + SLOT_KEYS.map(cstr).join(', ') + '};');
SLOT_KEYS.forEach(function (k) {
  o.push('static const char* const kOpt_' + k + '[] = {' + Recipe.SLOTS[k].map(cstr).join(', ') + '};');
});
o.push('const char* const* const kSlotOptions[kNumSlots] = {' + SLOT_KEYS.map(function (k) { return 'kOpt_' + k; }).join(', ') + '};');
o.push('const uint8_t kSlotOptionCount[kNumSlots] = {' + SLOT_KEYS.map(function (k) { return Recipe.SLOTS[k].length; }).join(', ') + '};');
o.push('const char* const kColorKeys[kNumColors] = {' + Recipe.COLORS.map(cstr).join(', ') + '};');
o.push('const char* const kNumberKeys[kNumNumbers] = {' + NUM_KEYS.map(cstr).join(', ') + '};');
o.push('const float kNumberRange[kNumNumbers][2] = {' + NUM_KEYS.map(function (k) {
  return '{' + num(Recipe.NUMBERS[k][0]) + ', ' + num(Recipe.NUMBERS[k][1]) + '}';
}).join(', ') + '};');
o.push('');

function recipeInit(r) {
  var slots = SLOT_KEYS.map(function (k) {
    var i = Recipe.SLOTS[k].indexOf(r[k]);
    if (i < 0) throw new Error('bad slot ' + k);
    return i;
  });
  var cols = Recipe.COLORS.map(function (k) { return hex(r[k]); });
  var nums = NUM_KEYS.map(function (k) { return num(r[k]); });
  return '{' + cstr(r.name) + ', ' + slots.join(', ') + ', ' + cols.join(', ') + ', ' + nums.join(', ') + '}';
}
if (Recipe.PRESET_ORDER[0] !== 'classic') throw new Error('classic must be the first preset (baseRecipe)');
o.push('const PresetDef kPresets[] = {');
Recipe.PRESET_ORDER.forEach(function (id) {
  var r = Recipe.PRESETS[id];
  o.push('  {' + cstr(id) + ', ' + (Recipe.PRESET_KIND[id] === 'cat') + ', ' + recipeInit(r) + ', ' +
    cstr(Recipe.toCode(r)) + '},');
});
o.push('};');
o.push('const int kNumPresets = ' + Recipe.PRESET_ORDER.length + ';');
o.push('');

// moods
var ICON = { '': 'Icon::None', heart: 'Icon::Heart', star: 'Icon::Star', spiral: 'Icon::Spiral', x: 'Icon::X',
  battery: 'Icon::Battery', question: 'Icon::Question', money: 'Icon::Money' };
var PART = { heart: 'Heart', zzz: 'Zzz', sweat: 'Sweat', sparkle: 'Sparkle', confetti: 'Confetti', question: 'Question',
  exclaim: 'Exclaim', steam: 'Steam', music: 'Music', dizzyStar: 'DizzyStar', tear: 'Tear', puff: 'Puff' };
var KIND = { sin: 'MOTION_SIN', jitter: 'MOTION_JITTER', hop: 'MOTION_HOP', rumble: 'MOTION_RUMBLE' };

function faceArr(name, face) {
  var parts = [], icon = 'Icon::None';
  Object.keys(face).forEach(function (k) {
    if (k === 'icon') { icon = ICON[face[k]]; if (!icon) throw new Error('icon ' + face[k]); return; }
    if (FP.FIELDS.indexOf(k) < 0) throw new Error('unknown field ' + k);
    parts.push('{F_' + k + ', ' + num(face[k]) + '}');
  });
  if (!parts.length) parts.push('{F_smile, ' + num(FP.DEFAULTS.smile) + '}');
  o.push('static const FieldValue ' + name + '[] = {' + parts.join(', ') + '};');
  return { n: parts.length, icon: icon };
}

var defs = [];
Moods.MOODS.forEach(function (id) {
  var dog = faceArr('kDog_' + id, Moods.getFace(id, 'dog'));
  var cat = faceArr('kCat_' + id, Moods.getFace(id, 'cat'));
  var mot = Moods.MOTION[id] || [];
  if (mot.length) {
    o.push('static const MotionDef kMot_' + id + '[] = {' + mot.map(function (m) {
      if (FP.FIELDS.indexOf(m[0]) < 0) throw new Error('motion field ' + m[0]);
      return '{F_' + m[0] + ', ' + num(m[1]) + ', ' + num(m[2]) + ', ' + KIND[m[3]] + ', ' + num(m[4] || 0) + '}';
    }).join(', ') + '};');
  }
  var ex = Moods.EXTRAS[id], exs = '{nullptr, 0, false, 0.0f, Particle::Sparkle, 0.0f, 0.0f, 0.0f}';
  if (ex) {
    var en = 'nullptr', nEn = 0;
    if (ex.enter) {
      o.push('static const ExtraEnter kEnter_' + id + '[] = {' + ex.enter.map(function (e) {
        return '{Particle::' + PART[e[0]] + ', ' + num(e[1]) + ', ' + num(e[2]) + ', ' + (e[3] || 1) + '}';
      }).join(', ') + '};');
      en = 'kEnter_' + id; nEn = ex.enter.length;
    }
    var ev = ex.every;
    exs = '{' + en + ', ' + nEn + ', ' + (ev ? 'true' : 'false') + ', ' + (ev ? num(ev[0]) : '0.0f') + ', Particle::' +
      (ev ? PART[ev[1]] : 'Sparkle') + ', ' + (ev ? num(ev[2]) : '0.0f') + ', ' + (ev ? num(ev[3]) : '0.0f') + ', ' +
      (ev ? num(ev[4] || 0) : '0.0f') + '}';
  }
  defs.push('  {' + [cstr(id), cstr(Moods.LABELS[id]), 'kDog_' + id, dog.n, dog.icon, 'kCat_' + id, cat.n, cat.icon,
    mot.length ? 'kMot_' + id : 'nullptr', mot.length, exs, Moods.followsLook(id)].join(', ') + '},');
});
if (Moods.MOODS[0] !== 'neutral') throw new Error('neutral must be mood 0');
o.push('');
o.push('const MoodDef kMoods[] = {');
o.push.apply(o, defs);
o.push('};');
o.push('const int kNumMoods = ' + Moods.MOODS.length + ';');
o.push('');
o.push('}  // namespace spike');
fs.writeFileSync(path.join(OUT, 'spike_tables_gen.cpp'), o.join('\n') + '\n');
console.log('wrote spike_fields.inc (' + FP.FIELDS.length + ' fields) and spike_tables_gen.cpp (' +
  Recipe.PRESET_ORDER.length + ' presets, ' + Moods.MOODS.length + ' moods)');
