# Desk Buddy guide - troubleshooting: (symptom, likely cause, fix). Full sentences (read aloud).
TROUBLE = [
    ('Nothing happens when I switch on.',
     'The protection board is asleep, the fuse has blown, or a cell is in the wrong way round.',
     'Switch off. Measure P+ to P- at the protection board: 0 V means it is asleep, so plug the USB-C charger in for a few seconds. If it still reads 0 V, check the fuse and the cells\' + and - marks.'),
    ('The fuse blows as soon as I switch on.',
     'A short circuit after the fuse: a bare wire end, a solder blob, or a screw tip touching a board.',
     'Take the fuse out. With the multimeter on beeper mode, test the switched battery wire to GND, then each 5 V module output to GND. Look for the joint that beeps and fix it before you fit a new fuse.'),
    ('The screen board restarts when the legs move.',
     'The servos pull the 5 V line down. Either the two 5 V modules are sharing a job, or a capacitor is missing.',
     'Check that module #1 feeds only the servo boards and module #2 only the screen and camera boards, and that each has its 1000 uF capacitor, stripe to minus.'),
    ('The screen board restarts when the lasers start up.',
     'Seven lasers plus the other sensors ask too much of the screen board\'s 3.3 V supply.',
     'Measure the 3.3 V rail while it happens. If it dips below 3.1 V, move the lasers\' VIN to the 5 V boards rail, but only after checking that each laser\'s SDA and SCL pins still read 3.3 V or less. Otherwise add a separate 3.3 V module.'),
    ('One servo does nothing.',
     'Its plug is on the wrong channel or board, or upside down.',
     'Check the servo channel table. The brown wire goes on the GND row. Use the servo sketch: press n until that servo is selected and watch whether it wiggles.'),
    ('Every servo is limp.',
     'No 5 V on the servo boards\' green terminal, or the wheel-stop (OE) line is high.',
     'Measure V+ to GND on each green terminal: about 5 V. Then check the green OE wire goes to IO14 and the 2.2 kOhm resistor goes to 3.3 V. In the servo sketch, press c.'),
    ('A servo board is "NOT FOUND".',
     'No 3.3 V on its VCC pin, SDA and SCL swapped or loose, or (board B) the A0 pad is not bridged.',
     'Measure 3.3 V on VCC. Re-seat the SDA and SCL wires. Board B must show 0x41 in the scan; if both boards show as 0x40, bridge A0 on board B.'),
    ('A wheel keeps creeping when it should stop.',
     'Every 360 degree servo has its own stop point, a little away from 1500 us.',
     'Find the stop point with + and - in the servo sketch and write it in the calibration table. The firmware uses that number.'),
    ('A leg is not straight when its servo is centred.',
     'The horn went onto the spline one tooth off, or the servo was turned by hand after centring.',
     'Small errors are fixed with the trim in the calibration table. If the error is bigger than about half a tooth, take the horn screw out, lift the horn off, and refit it one tooth over.'),
    ('A servo buzzes or gets warm while standing still.',
     'It is pushing against a stop: a lead is pinched, a part rubs, or its trim asks for a pose it cannot reach.',
     'Switch off, move the joint by hand to find what catches, and re-lay any lead. Check the joint limits for the back legs.'),
    ('A laser reads a short distance all the time.',
     'The protective film is still on the chip, or the chip is not centred in its window.',
     'Peel the film off. Re-seat the board so the chip sits in the middle of the window, and keep the window clean.'),
    ('Only one laser answers, or none.',
     'All seven lasers start at the same address. The firmware wakes them one by one using the XSHUT wires.',
     'Run l in the servo sketch. A laser that shows NO ANSWER has a loose XSHUT, SDA, SCL, VIN or GND wire, or its XSHUT is on the wrong channel of board B.'),
    ('Touch does not register.',
     'A foil pad is not clamped to its wire, or the MPR121 is not seen on the bus.',
     'With the power off, check each pad wire beeps to its foil. Check 0x5A shows in the I2C scan.'),
    ('The microphones hear nothing, or left and right are swapped.',
     'Glue over the sound holes, a wrong pin on P3, or both mics with the same L/R setting.',
     'Check the sound holes are open. One mic\'s L/R pin goes to GND and the other\'s to 3.3 V. Check the three data lines against the signal table.'),
    ('No sound from the speaker.',
     'The speaker is not in the "Speak" port, or a speaker wire was connected to ground.',
     'Plug it into "Speak" only. Never connect either speaker wire to GND.'),
    ('The laptop cannot find the board, or the upload fails.',
     'A charge-only USB cable, or the board is also powered through P1.',
     'Unplug the 5 V lead from P1 first. Try the phone cable test from the parts check: if the phone does not show up on the laptop, the cable is charge-only. Hold BOOT while you plug the cable in to force upload mode.'),
    ('The Serial Monitor stays empty after an upload.',
     'The screen board\'s USB-C goes to the chip\'s own USB port, not to a USB-serial chip.',
     'In tools/servo_center/platformio.ini change ARDUINO_USB_CDC_ON_BOOT=0 to 1, upload again, and reopen the monitor.'),
    ('A cover or panel will not snap shut.',
     'A lead is trapped under its edge, or a print blob sits in the hook window.',
     'Never force it. Open it, re-lay the lead in its channel, and clean the hook windows with the flush cutters.'),
    ('A screw spins without tightening.',
     'The pilot hole is stripped.',
     'Take the screw out, put a drop of superglue in the hole, let it set for ten minutes, and drive the screw in gently. A heat-set insert is the long-term fix for covers you open often.'),
    ('The knee pods get hot.',
     'The knees work hard when the robot stands for a long time, and the pods are closed plastic.',
     'Check with a thermocouple. Stop and let the robot cool above 45 degrees C. Let it sit or lie down between walks.'),
    ('The robot tips when it lifts a foot.',
     'The weight is not where the design expects: a heavy item moved, or the cells are different.',
     'Check the hub and the battery sit in their fences. The firmware shifts the body about 8 mm before lifting a front foot; do not lift a foot without that shift.'),
    ('The battery runs down fast.',
     'Old or mismatched cells, or the servos hold a pose against a stop.',
     'Charge both cells fully, check they are within 0.05 V, and look for a buzzing servo. Use the spare pair to compare.'),
]
