# Desk Buddy guide - parts data (printed parts, plates, bought parts, screws).
# Sources: cad/print_v3_1_README.md (printed parts, plates, screws - the master),
#          shopping/DeskBuddy_Parts_List.html (what was bought, 26 Sep 2026, with the links).
# Colour words are never written here: 'white' / 'graphite' / 'black' are keys into config.COLOURS.
# Each printed part's colour key comes from config.part_colour (PART_COLOUR_RULES) - see the end of this file.
import config

# (file name, friendly name, colour key, what it holds, grams each, plate, count, picture file)
PRINTED = [
    ('Torso_Bottom', 'the tub', 'graphite', '4 hip servos, 2 servo boards, protection board, fuse, USB-C charger, power switch, 5 laser sensors', 49.7, 'G1', 1,
     'Torso_Bottom (4 hip MG90S, 2 PCA9685, protection board, fuse holder, USB-C charger, KCD1, 5 VL53L0X).png'),
    ('Band_Chest', 'chest band', 'graphite', 'front laser window; hides 2 lid screws (snaps on)', 3.5, 'G1', 1,
     'Band_Chest (front obstacle VL53L0X window, covers 2 lid screws).png'),
    ('Band_Rump', 'rump band', 'graphite', 'rear laser window and the USB-C opening; hides 2 lid screws', 3.4, 'G1', 1,
     'Band_Rump (rear obstacle VL53L0X window, USB-C port, covers 2 lid screws).png'),
    ('Side_Panel_Left / _Right', 'side panels', 'graphite', 'cover the 2 hip servos on each side (4 snap hooks, no screws)', 14.9, 'G2', 2,
     'Side_Panel_Left (covers the 2 left hip MG90S).png'),
    ('Battery_Door', 'battery door', 'graphite', 'the 2 x 18650 holder and its clamp; 4 screws into the tub', 11.1, 'G2', 1,
     'Battery_Door (18650 holder, battery clamp).png'),
    ('Battery_Clamp', 'battery clamp', 'graphite', 'holds the cell holder down', 1.3, 'G2', 1,
     'Battery_Clamp (holds the 18650 holder down).png'),
    ('Collar', 'collar (neck)', 'graphite', 'nothing - cables pass through it; joins the lid to the head', 12.4, 'G2', 1,
     'Collar (cables only).png'),
    ('Torso_Lid', 'the lid', 'white', 'motion sensor, touch board, perfboard hub, tail servo, 2 side lasers, 4 touch pads', 46.0, 'W1', 1,
     'Torso_Lid (MPU6050, MPR121, perfboard hub with 2 Mini560, tail MG90S, 2 side VL53L0X, touch pads).png'),
    ('Tail_Root', 'tail root', 'white', 'the tail servo horn and the tail cap', 1.6, 'W1', 1,
     'Tail_Root (tail cross horn, tail cap).png'),
    ('Tail', 'tail', 'white', 'nothing (keyed onto the root, 1 hidden screw)', 1.1, 'W1', 1,
     'Tail (decorative, keyed onto the tail root).png'),
    ('Ear_Left / Ear_Right', 'ears', 'white', 'nothing (1 screw each from inside the head)', 2.5, 'W1', 2,
     'Ear_Left (decorative).png'),
    ('Head_Front', 'head front', 'white', '4.3 inch screen, 2 microphones, head touch pad, both ears', 35.8, 'W2', 1,
     'Head_Front (Guition 4.3in screen, 2 MS3625 mics, touch pad).png'),
    ('Muzzle', 'muzzle', 'white', 'camera board, camera, gesture sensor', 11.4, 'W2', 1,
     'Muzzle (ESP32-S3 CAM, OV5640 camera, APDS-9960).png'),
    ('Head_Back', 'head back', 'white', 'the speaker; clips onto the head front (5 snap hooks)', 31.0, 'W3', 1,
     'Head_Back (cavity speaker).png'),
    ('Thigh_<leg>_Outer', 'thigh outer halves', 'white', 'hip horn, knee servo (2 tab screws), 2 snap hooks', 7.3, 'W3 + W4', 4,
     'Thigh_FrontLeft_Outer (knee MG90S tabs, hip cross horn).png'),
    ('Shin_<leg>_Outer', 'shin outer halves', 'white', 'knee horn, wheel servo (2 tab screws), 2 snap hooks', 9.0, 'W4', 4,
     'Shin_FrontLeft_Outer (wheel MG90S 360 tabs, knee cross horn).png'),
    ('Thigh_<leg>_Cover', 'thigh covers', 'graphite', 'the knee servo body (in the knee pod) and its leads', 7.2, 'G3', 4,
     'Thigh_FrontLeft_Cover (knee MG90S case, leads).png'),
    ('Shin_<leg>_Cover', 'shin covers', 'graphite', 'the wheel servo body (in the paw pod), leads, knee lead ring', 8.1, 'G4', 4,
     'Shin_FrontLeft_Cover (wheel MG90S 360 case, leads).png'),
    ('Wheel_<leg>', 'wheels', 'graphite', 'the wheel horn and a 26 x 2.4 mm O-ring tyre', 2.9, 'G3 + G4', 4,
     'Wheel_FrontLeft (wheel cross horn, 26x2.4 O-ring tyre).png'),
    ('Cap_Hip_<leg>, Cap_Knee_<leg>', 'hip and knee caps (12 mm)', 'black', 'hide the hip and knee horn screws', 0.2, 'B1', 8,
     'Cap_Hip_FrontLeft (covers the hip horn screw).png'),
    ('Cap_Wheel_<leg>', 'wheel caps (14 mm)', 'black', 'hide the wheel horn screws', 0.3, 'B1', 4,
     'Cap_Wheel_FrontLeft (covers the wheel horn screw).png'),
    ('Cap_Tail', 'tail cap (12 mm)', 'black', 'hides the tail horn screw', 0.2, 'B1', 1,
     'Cap_Tail (covers the tail horn screw).png'),
    ('Port_Door_Head, Port_Blank_Head', 'head port door + blank', 'black', 'cover for the screen board USB-C, and its matching blank', 0.3, 'B1', 2,
     'Port_Door_Head (covers the screen USB-C).png'),
    ('Port_Door_Muzzle, Port_Blank_Muzzle', 'muzzle port door + blank', 'black', 'cover for the camera board USB-C, and its matching blank', 0.4, 'B1', 2,
     'Port_Door_Muzzle (covers the camera USB-C).png'),
    ('Screw_Plugs', 'screw plugs (4 in one file)', 'black', 'hide the 4 battery-door screws', 0.1, 'B1', 1,
     'Screw_Plugs (cover the 4 battery door screws).png'),
    ('Screen_Washers', 'screen washers (4 in one file)', 'black', 'go under the 4 screen screws', 0.1, 'B1', 1,
     'Screen_Washers (4 washers under the Guition screen screws).png'),
]

TEST_PRINTS = [
    ('Fit_Test_Coupon', 'servo slot, power-switch cut-out, screen boss, sensor windows, O-ring groove, horn pocket', 14.5,
     'Fit_Test_Coupon (print first - servo slot, switch, screen boss, windows, O-ring groove, horn pocket).png'),
    ('Coupon_Knee_Thigh', 'knee servo tabs and case (screw a real MG90S to it)', 3.0,
     'Coupon_Knee_Thigh (knee MG90S - test print).png'),
    ('Coupon_Knee_Shin', 'knee cross horn, cap and lead chamber', 5.6,
     'Coupon_Knee_Shin (knee cross horn, lead chamber - test print).png'),
    ('Coupon_Snap_White', 'one snap hook, a 12 mm and a 14 mm cap seat', 2.3,
     'Coupon_Snap_White (snap hook, cap seats - test print).png'),
    ('Coupon_Snap_Graphite', 'the snap catch for the hook', 0.6,
     'Coupon_Snap_Graphite (snap catch - test print).png'),
]

# (order, plate, colour key or None for any, parts, grams, band price, per-10 g price)
PLATES = [
    (1, 'T1', None, 'Fit_Test_Coupon, both knee coupons, both snap coupons, 1 x 12 mm + 1 x 14 mm cap', 26.5, '$4.00', '$2.92'),
    (2, 'B1', 'black', '13 caps, 4 port doors and blanks, screw plugs, screen washers', 4.6, '$1.00', '$0.51'),
    (3, 'G1', 'graphite', 'tub + 2 bands', 56.6, '$6.00', '$6.23'),
    (4, 'W1', 'white', 'lid + 2 ears + tail root + tail', 53.7, '$6.00', '$5.91'),
    (5, 'G2', 'graphite', '2 side panels + battery door + clamp + collar', 54.6, '$6.00', '$6.01'),
    (6, 'W2', 'white', 'head front + muzzle', 47.2, '$6.00', '$5.19'),
    (7, 'W3', 'white', 'head back + 1 thigh outer', 38.3, '$4.00', '$4.21'),
    (8, 'W4', 'white', '4 shin outers + 3 thigh outers', 57.9, '$6.00', '$6.37'),
    (9, 'G3', 'graphite', '4 thigh covers + 3 wheels', 37.5, '$4.00', '$4.12'),
    (10, 'G4', 'graphite', '4 shin covers + 1 wheel', 35.3, '$4.00', '$3.88'),
]

# Every printed file, for the tick-off checklist: (plate, file)
CHECKLIST = [
    ('T1', 'Fit_Test_Coupon'), ('T1', 'Coupon_Knee_Thigh'), ('T1', 'Coupon_Knee_Shin'), ('T1', 'Coupon_Snap_White'),
    ('T1', 'Coupon_Snap_Graphite'),
    ('B1', 'Cap_Hip_FrontLeft'), ('B1', 'Cap_Hip_FrontRight'), ('B1', 'Cap_Hip_BackLeft'), ('B1', 'Cap_Hip_BackRight'),
    ('B1', 'Cap_Knee_FrontLeft'), ('B1', 'Cap_Knee_FrontRight'), ('B1', 'Cap_Knee_BackLeft'), ('B1', 'Cap_Knee_BackRight'),
    ('B1', 'Cap_Wheel_FrontLeft'), ('B1', 'Cap_Wheel_FrontRight'), ('B1', 'Cap_Wheel_BackLeft'), ('B1', 'Cap_Wheel_BackRight'),
    ('B1', 'Cap_Tail'), ('B1', 'Port_Door_Head'), ('B1', 'Port_Blank_Head'), ('B1', 'Port_Door_Muzzle'),
    ('B1', 'Port_Blank_Muzzle'), ('B1', 'Screw_Plugs (4)'), ('B1', 'Screen_Washers (4)'),
    ('G1', 'Torso_Bottom'), ('G1', 'Band_Chest'), ('G1', 'Band_Rump'),
    ('W1', 'Torso_Lid'), ('W1', 'Ear_Left'), ('W1', 'Ear_Right'), ('W1', 'Tail_Root'), ('W1', 'Tail'),
    ('G2', 'Side_Panel_Left'), ('G2', 'Side_Panel_Right'), ('G2', 'Battery_Door'), ('G2', 'Battery_Clamp'), ('G2', 'Collar'),
    ('W2', 'Head_Front'), ('W2', 'Muzzle'),
    ('W3', 'Head_Back'), ('W3', 'Thigh_FrontLeft_Outer'),
    ('W4', 'Thigh_FrontRight_Outer'), ('W4', 'Thigh_BackLeft_Outer'), ('W4', 'Thigh_BackRight_Outer'),
    ('W4', 'Shin_FrontLeft_Outer'), ('W4', 'Shin_FrontRight_Outer'), ('W4', 'Shin_BackLeft_Outer'), ('W4', 'Shin_BackRight_Outer'),
    ('G3', 'Thigh_FrontLeft_Cover'), ('G3', 'Thigh_FrontRight_Cover'), ('G3', 'Thigh_BackLeft_Cover'), ('G3', 'Thigh_BackRight_Cover'),
    ('G3', 'Wheel_FrontLeft'), ('G3', 'Wheel_FrontRight'), ('G3', 'Wheel_BackLeft'),
    ('G4', 'Shin_FrontLeft_Cover'), ('G4', 'Shin_FrontRight_Cover'), ('G4', 'Shin_BackLeft_Cover'), ('G4', 'Shin_BackRight_Cover'),
    ('G4', 'Wheel_BackRight'),
]

AE = 'https://www.aliexpress.com/item/'
# (part, qty, where it goes, link, store, key) - 'key' lets the steps refer to a part
BOUGHT = [
    ('Guition ESP32-S3 4.3" touchscreen board (JC4827W543C)', '1', 'Head front, behind the screen window', AE + '1005006729377800.html', 'AliExpress', 'screen'),
    ('ESP32-S3 N16R8 camera board + OV5640 camera', '1', 'Muzzle (lens in the left window)', AE + '1005009210809394.html', 'AliExpress', 'cam'),
    ('ESP32-S3-DevKitC-1 N16R8', '1', 'Not fitted - bench spare', AE + '1005010373962338.html', 'AliExpress', 'devkit'),
    ('MG90S metal-gear servo, 180 degrees', '10', '4 hips, 4 knees, tail, 1 spare', AE + '1005006860780474.html', 'AliExpress', 'mg90s'),
    ('MG90S metal-gear servo, 360 degrees (continuous)', '4', 'Wheels, one in each paw', AE + '1005012187908480.html', 'AliExpress', 'mg90s360'),
    ('PCA9685 16-channel servo board', '2', 'Tub, one on each side wall', AE + '1005010706769492.html', 'AliExpress', 'pca'),
    ('VL53L0X laser distance sensor', '8', '7 fitted (chest, rump, 3 desk-edge in the tub floor, 2 sides in the lid) + 1 spare', AE + '1005008660383200.html', 'AliExpress', 'vl53'),
    ('MS3625 I2S microphone', '2', 'Mic rings on each side of the head front', AE + '1005009213592784.html', 'AliExpress', 'mic'),
    ('Cavity speaker 3 W 4 ohm (1.25 mm plug)', '1', 'Head back, between its fences', AE + '1005009465741899.html', 'AliExpress', 'speaker'),
    ('MPU6050 motion sensor (GY-521)', '1', 'Under the lid, in its fence', AE + '1005007169577953.html', 'AliExpress', 'mpu'),
    ('APDS-9960 gesture sensor', '1', 'Muzzle, on its shelf behind the right window', AE + '1005008247999939.html', 'AliExpress', 'apds'),
    ('MPR121 touch board', '1', 'Under the lid, in its fence', AE + '1005010759757874.html', 'AliExpress', 'mpr'),
    ('Type-C 2S boost charging board', '1', 'Tub, raised ledge at the rump; socket in the rump opening', AE + '1005010706867355.html', 'AliExpress', 'charger'),
    ('2S 20 A protection board (with balance)', '1', 'Tub floor, between its fences', AE + '1005006995181873.html', 'AliExpress', 'bms'),
    ('2 x 18650 battery holder (series, wired)', '1', 'Battery door', AE + '1005007170299017.html', 'AliExpress', 'holder'),
    ('Mini560 buck converter, fixed 5 V 5 A', '2', 'On the perfboard hub under the lid', AE + '1005007937920693.html', 'AliExpress', 'buck'),
    ('KCD1 rocker switch', '1', 'Front of the belly, flush in its recess', AE + '4000125268992.html', 'AliExpress', 'switch'),
    ('Mini blade fuse holder, 7.5 A, 16 AWG', '1', 'On top of the protection board', AE + '1005005625637629.html', 'AliExpress', 'fuse'),
    ('M2 self-tapping screw kit (500)', '1', 'Everywhere - see the screw chart', AE + '1005006904470760.html', 'AliExpress', 'screws'),
    ('Dupont jumper wires (120)', '1', 'Signal wiring', AE + '1005007791660521.html', 'AliExpress', 'dupont'),
    ('MX1.25 4-pin pre-wired plugs (10)', '1', 'Plugs for the screen board ports P1, P3, P4', AE + '1005007277110532.html', 'AliExpress', 'mx125'),
    ('Perfboard 5 x 7 cm (5)', '1', 'The power and sensor hub under the lid', AE + '1005007024264426.html', 'AliExpress', 'perf'),
    ('3M double-sided foam tape, 20 mm', '1', 'Sensor boards and the hub', AE + '1005007010049062.html', 'AliExpress', 'tape'),
    ('Heat-shrink tubing (127)', '1', 'Every soldered joint', AE + '1005008728485990.html', 'AliExpress', 'shrink'),
    ('830-point breadboard', '1', 'Tool: bench test', AE + '1005007345339483.html', 'AliExpress', 'bb'),
    ('ES02 soldering kit + digital multimeter', '1', 'Tool', AE + '1005007170830774.html', 'AliExpress', 'iron'),
    ('PLATO 170 flush cutters', '1', 'Tool', AE + '1005004257411917.html', 'AliExpress', 'cutters'),
    ('Digital caliper 150 mm', '1', 'Tool: measure the servos before printing', AE + '1005005671598813.html', 'AliExpress', 'caliper'),
    ('Samsung 35E 18650 cell, 3500 mAh, button top', '2', 'In the battery holder', 'https://www.tinkertechau.com.au/products/samsung-35e-18650-3500mah-10a-battery-button-top', 'TinkerTech AU', 'cells'),
    ('Tinker 25R 18650 cell, 2500 mAh (spare pair)', '2', 'Spare pair - never mix with the Samsungs', 'https://www.tinkertechau.com.au/products/tinker-25r-18650-2500mah-20a-battery', 'TinkerTech AU', 'spares'),
    ('Heavy-duty hook-up wire 7.5 A, red (WH3040)', '2 m', 'Battery and servo power (+)', 'https://www.jaycar.com.au/p/WH3040', 'Jaycar', 'redwire'),
    ('Heavy-duty hook-up wire 7.5 A, black (WH3041)', '2 m', 'Battery and servo power (-)', 'https://www.jaycar.com.au/p/WH3041', 'Jaycar', 'blackwire'),
    ('1000 uF 16 V capacitor (RE6220)', '2', 'Hub: one across each Mini560 output', 'https://www.jaycar.com.au/p/RE6220', 'Jaycar', 'cap'),
    ('2.2 kOhm resistors (RR0580)', '1 pack', 'Hub: wheel-stop pull-up on the OE line', 'https://www.jaycar.com.au/p/RR0580', 'Jaycar', 'r22k'),
    ('10 kOhm resistors (RR0596)', '1 pack', 'Hub: battery-level divider (top)', 'https://www.jaycar.com.au/p/RR0596', 'Jaycar', 'r10k'),
    ('4.7 kOhm resistors (RR0588)', '1 pack', 'Hub: battery-level divider (bottom)', 'https://www.jaycar.com.au/p/RR0588', 'Jaycar', 'r47k'),
    ('NBR O-ring assortment, OD 21-35 mm x 2.4 mm CS', '1', 'Wheel tyres: use the 31 mm OD rings (about 26.2 mm inside), 4 + spares', '', 'AliExpress', 'orings'),
    ('Superglue 3 g (6 pack)', '1', 'Only where the guide says', '', 'Bunnings', 'glue'),
    ('Cable ties 100 mm (25)', '1', 'Hub anchors, slack loops', '', 'Bunnings', 'ties'),
]

# Screws: (where, count, size, note) - cad/print_v3_1_README.md "Screws"
SCREWS = [
    ('Hip servo tabs into the tub wall (from outside, under the side panels)', 8, 'M2x6', 'servo bag screws fit'),
    ('Knee and wheel servo tabs into the leg outer halves', 16, 'M2x6', 'from the tab side into blind holes'),
    ('Tail servo tabs into the two ribs under the lid', 2, 'M2x6', 'driven up from inside'),
    ('PCA9685 boards onto the upper two standoffs each', 4, 'M2x6', 'the lower standoffs are spacers only'),
    ('Horn arms into the thighs (hip horns)', 8, 'M2x4', 'use horn holes 6.7-10 mm from the centre'),
    ('Horn arms into the shins (knee horns)', 8, 'M2x6', ''),
    ('Horn arms into the wheels', 8, 'M2x6', 'outer horn holes (7.6 mm or more from the centre)'),
    ('Horn arms into the tail root', 2, 'M2x4', 'the root is only 4.6 mm thick'),
    ('Horn onto each servo spline (13 outputs)', 13, 'horn', "the servo's own horn screw, then press the cap in"),
    ('Thigh and shin covers', 8, 'M2x8', 'thigh: bottom of the knee disc; shin: under the wheel'),
    ('Lid to tub, through the chest and rump walls', 4, 'M2x6', 'hidden by the snap-on bands'),
    ('Lid to collar, from inside the lid', 4, 'M2x8', 'before the lid goes on the tub'),
    ('Head to collar, from inside the head', 4, 'M2x8', 'before the head back goes on'),
    ('Muzzle to head, from inside the head', 4, 'M2x8', ''),
    ('Screen to the head front, through the 4 printed washers', 4, 'M2x6', ''),
    ('Ears, from inside the head', 2, 'M2x8', ''),
    ('Battery door to tub (heads under the plugs)', 4, 'M2x6', ''),
    ('Battery clamp onto the door posts', 2, 'M2x8', ''),
    ('Touch pads: foil tab and wire clamped under the screw', 5, 'M2x4', '4 under the lid, 1 under the head top'),
    ('Tail onto the tail root, from under the root', 1, 'M2x8', 'before the root goes onto the servo'),
]
SCREW_TOTALS = {'M2x4': 15, 'M2x6': 58, 'M2x8': 25, 'horn': 13}


# one place for part colours: rewrite the colour key of every PRINTED row from config.PART_COLOUR_RULES
PRINTED = [(f, nm, config.part_colour(f), holds, g, pl, n, pic) for f, nm, _c, holds, g, pl, n, pic in PRINTED]
