# Desk Buddy guide - assembly steps, part 4: G Close up, and chapter 7 First power-on (P steps).
TUB = ('Torso_Bottom', 'graphite', (0, 0, 0))

STEPS_G = [
    dict(id='G1', title='Connect every lead', fig_mm=92,
         img=('render', 'Desk Buddy v3.1 - full assembly - inside (shells see-through).png', None),
         need=[('part', 'Wiring tables: power, signals, servo channels, lasers'), ('part', 'cable ties')],
         text=['With the lid standing on its side next to the tub, connect everything, one table row at a time, and tick each row off in the Wiring chapter.',
               'Servo leads: each plugs into its channel on the servo board on its own side (servo channel table), with the brown wire on the GND row at the bottom of the header and the orange wire on the PWM row at the top. The tail servo goes to board A, channel 8.',
               'Laser XSHUT wires go to board B, channels 9 to 15. Power and sensor leads from the tub go to the hub under the lid. Leave each tub-to-lid lead about 10 cm longer than it needs to be, so the lid can stand beside the tub while you work.',
               'Tie slack loops with small cable ties, away from the servo horns and from the battery door opening.'],
         check='Go through every table row once more with a finger on each plug. Every plug is fully home and no pin shows.',
         mistake='Plugging a servo lead in upside down. The servo then does nothing; it is not damaged, just turn the plug round.'),

    dict(id='G2', title='Lid onto the tub',
         img=('stl', dict(parts=[TUB, ('Side_Panel_Left', 'graphite', (0, 0, 0)), ('Torso_Lid', 'white', (0, 28, 0)),
                                 ('Collar', 'graphite', (0, 28, 0))], cam=(24, 32), width=1500, hi=['Torso_Lid'],
                          arrows=[((-20, 88, 0), (-20, 66, 0))],
                          labels=[((42, 31, 66), 'hip leads lie in the notch; the lid\'s comb clamps them', 'a'),
                                  ((25, 32.5, 80), 'lid screws: 2 x M2x6 through the chest wall', 'a'),
                                  ((0, 70, 0), 'lid (lower it straight down)', 'a')])),
         need=[('screw', 4, 'M2x6')],
         text=['Check that every hip lead lies flat in its notch at the top of the tub wall, and that no lead crosses the tub\'s top edge anywhere else.',
               'Lower the lid straight down onto the tub. Its lip slides inside the tub wall and its combs press the leads into the notches.',
               'Drive 2 x M2x6 through the chest wall and 2 x M2x6 through the rump wall into the lid\'s bosses.'],
         check='The seam between lid and tub is even all round, and the lid does not rock.',
         mistake='Closing the lid on a lead. If it does not sit down with a light press, lift it and find the lead.'),

    dict(id='G3', title='Chest and rump bands',
         img=('sec', '1 Body', dict(hi=['Band_Chest', 'Band_Rump'], arrows=[('Band_Chest', (120, -70)), ('Band_Rump', (-120, 70))],
                                   labels=[('Band_Chest', 'chest band (front laser window)', 'a', 0), ('Band_Rump', 'rump band (USB-C opening)', 'a', 0)])),
         need=[('part', 'chest band and rump band (no screws)')],
         text=['The bands hide the four lid screws. Each has two snap hooks.',
               'Press the chest band into its recess on the front of the tub, laser window over the front laser, until both hooks click. Do the same with the rump band at the back; its larger pill-shaped opening goes over the USB-C socket.'],
         check='Plug the USB-C cable in through the rump band: it goes fully home.',
         mistake='Putting the bands on the wrong ends. The rump band is the one with the USB-C opening.'),

    dict(id='G4', title='Head back on',
         img=('sec', '3 Head', dict(hi=['Head_Back'], arrows=[('Head_Back', (-120, 70))], labels=[('Head_Back', 'head back: 5 snap hooks', 'a', 0)])),
         need=[('part', 'head back with the speaker (step C7)')],
         text=['Check the speaker is plugged into the "Speak" port and no lead lies across the rim of the head front.',
               'Slide the head back\'s lip into the head front and press until all five hooks click: three along the top and two along the bottom.'],
         check='The groove between the two halves is even all round.',
         mistake='Squeezing a lead in the rim. The head back then will not sit flush; do not force it.'),
]

STEPS_P = [
    dict(id='7.1', title='Checks before the cells go in',
         img=('render', 'Desk Buddy v3.1 - full assembly - under.png', None),
         need=[('part', 'multimeter'), ('part', 'a block or mug to prop the robot on')],
         text=['Set the power switch to OFF. Set the multimeter to its beeper (continuity) mode.',
               'Touch the probes to the protection board\'s P+ and P- pads: it must not beep. Then to the output of each 5 V module on the hub: it must not beep. A beep means a short circuit. Find it before you go on.',
               'Stand the robot on a block so all four wheels are off the desk. It stays there for every first test.'],
         check='No beep on any power pair, and the fuse is in its holder.',
         mistake='Testing with the cells in. The beeper test is only safe with the power off and the cells out.'),

    dict(id='7.2', title='Cells in, protection board awake',
         img=('stl', dict(parts=[('Battery_Door', 'graphite', (0, 0, 0)), ('Battery_Clamp', 'graphite', (0, 0, 0))],
                          cam=(16, 55), width=1200, labels=[((0, 10, -40), 'cell 1: black lead to the middle link', 'a'),
                                                            ((0, 10, 5), 'cell 2: middle link to the red lead', 'a')])),
         need=[('part', '2 x Samsung 35E cells'), ('part', 'USB-C charger and cable')],
         text=['Measure each cell with the multimeter on DC volts. Each should read between 3.0 and 4.2 V, and the two must be within 0.05 V of each other. If not, charge them separately or use the spare pair; never mix a Samsung with a Tinker cell.',
               'Check the + and - marks in the holder twice. Put in first the cell that sits between the black lead and the middle wire, then the other one. This connects negative, then the middle, then positive, in the order the protection board needs.',
               'Plug the USB-C charger into the rump socket for a few seconds and unplug it. This wakes the protection board. Now measure between P+ and P-: you should see the two cell voltages added together, between 6.0 and 8.4 V.'],
         check='The two cells are the same model, the same charge, and the right way round.',
         mistake='Reading 0 V at P+ and P-. The protection board is still asleep: plug the charger in once more.'),

    dict(id='7.3', title='Battery door on',
         img=('stl', dict(parts=[TUB, ('Battery_Door', 'graphite', (0, -30, 0))], cam=(16, -48), width=1300,
                          hi=['Battery_Door'], arrows=[((0, -40, 40), (0, -12, 40))],
                          labels=[((23.4, -30, -48), 'door screw (4 x M2x6), then a plug over each head', 'a'),
                                  ((-23.4, -30, 18), 'door screw', 'a')])),
         need=[('screw', 4, 'M2x6'), ('part', '4 printed screw plugs')],
         text=['Tuck the battery leads in so nothing can be pinched, set the door into the belly opening, cells inside, and drive 4 x M2x6 into the lugs.',
               'Press a {{black}} plug over each screw head. To open the door later, prise the plugs out with a fingernail.'],
         check='The door sits flush with the belly.',
         mistake='Pinching the middle wire under the door edge.'),

    dict(id='7.4', title='First switch-on', fig_mm=140,
         img=('render', 'Desk Buddy v3.1 - full assembly - iso.png', None),
         need=[('part', 'laptop with the servo sketch (tools/servo_center)'), ('part', 'USB-C data cable')],
         text=['For the first switch-on the screen board runs the servo sketch from the Bench test chapter. Unplug the 5 V lead from port P1 (the rule: never two power sources on one board), then connect the laptop to the screen board\'s USB-C socket behind the head port door. The laptop now powers the screen board; the battery powers the servos.',
               'Open the Serial Monitor (pio device monitor) and switch the robot on. Within two seconds every leg should stiffen with the legs straight and the tail straight back, and the wheels should stay still or creep slowly.',
               'Type s and press Enter. The list must show 0x40 and 0x41 (both servo boards), 0x39 (gesture), 0x5A (touch) and 0x68 (motion). Type l to check all seven lasers answer one by one, and v to read the battery voltage.'],
         check='All thirteen servos hold still, nothing gets hot, and the battery reading matches the multimeter within about 0.2 V.',
         mistake='Leaving P1 plugged in while the USB cable is in.'),

    dict(id='7.5', title='If something does not move',
         img=None,
         need=[],
         text=['Switch off first, every time, before you touch a plug.',
               'One servo limp: its plug is on the wrong channel, on the wrong board, or upside down. Check the servo channel table; the brown wire goes on the GND row.',
               'Every servo limp: the servo boards are not getting 5 V, or the wheel-stop line is high. Measure between V+ and GND on each board\'s green terminal: it must read about 5 V. Then check the green OE wire goes to IO14 and the 2.2 kOhm resistor goes to 3.3 V, not to 5 V. Type c in the Serial Monitor to switch the outputs on again.',
               'A servo board "NOT FOUND": check its VCC reads 3.3 V, its SDA and SCL go to the right rails, and, for board B, that the A0 pad is bridged.',
               'A wheel keeps turning: it is normal for a 360 degree servo to creep at 1500 us. Find its real stop point in the next step.'],
         check='', mistake=''),

    dict(id='7.6', title='Calibrate every servo',
         img=None,
         need=[('part', 'the calibration table in this step'), ('part', 'a pencil')],
         text=['A horn fits on its spline only in steps of one tooth, so a leg that looks almost straight is normal. The firmware corrects the last few degrees with a trim for each servo, and this step finds those trims.',
               'In the Serial Monitor press n until the servo you want is selected (it wiggles). Press + or - to move it 10 us at a time until the leg is exactly straight, or the tail exactly straight back. Write the number in the table.',
               'For each wheel, press + or - until the wheel stops completely, and write that number down as its stop point.',
               'Finally, for each hip and knee, check which way plus moves it. Plus must move the foot forward, toward the head. If it moves back, write "reversed" in the table. The left and right legs are usually opposite.',
               'Before long walks, check how hot the knee pods get with the multimeter\'s thermocouple, if it has one: stop and let the robot cool above 45 degrees C.'],
         check='Every row of the table has a number.', mistake=''),

    dict(id='7.7', title='Charging and everyday care',
         img=None,
         need=[('part', '5 V, 2 A phone charger with a USB-A to USB-C cable')],
         text=['Switch the robot off, then plug the charger into the USB-C socket in the rump band. The robot cannot run while it charges.',
               'The firmware warns at 7.0 V and at 6.8 V parks the robot and switches the servos off. Charge it then; running the cells flatter shortens their life.',
               'To take the cells out, switch off, prise out the four plugs under the belly, and undo the four door screws. Always swap both cells together.'],
         check='', mistake=''),
]
