# Desk Buddy guide - assembly steps, part 2: C Head.
HF = ('Head_Front', 'white', (0, 0, 0))

STEPS_C = [
    dict(id='C1', title='Get to know the head front (inside)',
         img=('stl', dict(parts=[HF], cam=(160, 25), width=1500, labels=[
             ((56.3, 78.4, 73.1), 'screen screw boss (4)', 'a'),
             ((-56.3, 140.5, 73.1), 'screen screw boss', 'a'),
             ((61.4, 127.5, 59.5), 'microphone ring, left', 'a'),
             ((-61.4, 127.5, 59.5), 'microphone ring, right', 'a'),
             ((-62, 113, 67.4), 'port door opening (screen USB-C)', 'a'),
             ((0, 156.4, 58), 'head touch pad screw', 'a'),
             ((47.5, 156.4, 61), 'ear screw, left', 'a'),
             ((6, 61.5, 70), 'collar screws from inside (4)', 'a'),
             ((31, 70, 78.4), 'muzzle screws from inside (4)', 'a'),
         ])),
         need=[('part', 'head front (Head_Front)')],
         text=['The head front holds the screen, both microphones, the head touch pad and the ears, and the muzzle and collar screw to it from inside. Look inside it and find each place.',
               'Pre-thread the four screen bosses with an M2x6, then take the screw out again.'],
         check='The screen window\'s bevel is clean and the glass seat (the flat ledge round the window) has no blobs.',
         mistake='Leaving support or brim blobs on the glass seat. The screen then sits crooked and can crack when you screw it down.'),

    dict(id='C2', title='Screen into the head front', fig_mm=145,
         img=('sec', '3 Head', dict(crop='hi', hi2=['Guition screen'], hi=['Head_Front'], labels=[('Guition screen', 'screen board, glass forward', 'a', 0)])),
         need=[('part', 'Guition 4.3 inch screen board (tested)'), ('part', '4 printed screen washers'), ('screw', 4, 'M2x6')],
         text=['Lay the head front face down on a soft cloth. Put the screen board in, glass first, so the glass sits on the ledge round the window. The board\'s USB-C socket must face the robot\'s right side (your left as you look into the back of the head), next to the port door opening.',
               'Put a printed washer over each of the four corner holes and drive 1 x M2x6 through each into the bosses. Tighten in a cross pattern, and stop as soon as each screw is snug.',
               'Plug the 5 V lead into port P1 and the sensor lead into port P4 now, while you can still reach them.'],
         check='Turn the head over: the picture area sits evenly in the window, with no gap at any edge.',
         mistake='Over-tightening a corner screw. The glass is bonded to the board and cracks if the board bends.'),

    dict(id='C3', title='Microphones',
         img=('sec', '3 Head', dict(crop='hi', hi2=['MS3625 mic'], hi=['Head_Front'], labels=[('MS3625 mic', 'microphone in its ring', 'a', 0)])),
         need=[('part', '2 x MS3625 microphone, wired (Wiring, S11 and S12)'), ('part', 'superglue')],
         text=['Each microphone sits in the round ring on the inside of a side wall, with its sound hole facing the three tiny holes in the wall.',
               'Put a very small drop of superglue on the ring\'s rim, not near the holes, and press the microphone in, sound hole outward. Hold it for 20 seconds.',
               'The left microphone is the one with its L/R pin wired to GND.'],
         check='Hold the head up to a light: you can see light through the three holes, and nothing blocks them from inside.',
         mistake='Glue on the sound hole. The microphone is then deaf, and it cannot be cleaned.'),

    dict(id='C4', title='Head touch pad and port doors',
         img=('sec', '3 Head', dict(hi=['Port_Door_Head', 'Port_Blank_Head', 'Port_Door_Muzzle', 'Port_Blank_Muzzle'],
                                   labels=[('Port_Door_Head', 'head port door (robot\'s right)', 'a', 0), ('Port_Blank_Head', 'head blank (left)', 'a', 0),
                                           ('Port_Door_Muzzle', 'muzzle port door (left)', 'a', 0), ('Port_Blank_Muzzle', 'muzzle blank (right)', 'a', 0)])),
         need=[('part', 'foil piece about 20 x 15 mm and its grey wire (MPR121 E4)'), ('screw', 1, 'M2x4'), ('part', '4 {{black}} port doors and blanks')],
         text=['Head touch pad: lay the foil under the raised oval on the inside of the head\'s top, wrap the stripped wire end round an M2x4, and drive it through the foil tab into the pad hole, exactly as for the lid pads.',
               'Port doors: the door with the finger notch covers a USB-C socket and the plain blank matches it on the other side, so the head looks the same from both sides. Press the head door into the opening on the robot\'s right side, and the head blank into the left. The muzzle door goes on the robot\'s left of the muzzle and its blank on the right.'],
         check='Each door clicks in flush and comes out again with a fingernail in the notch.',
         mistake='Using an M2x6 for the touch pad: it comes through the top of the head.'),

    dict(id='C5', title='Muzzle: camera and gesture sensor', fig_mm=128,
         note='This step may change in the next version. The muzzle design is still being decided (the current muzzle, a forehead camera above the screen, a camera in a collar tag, or a smooth chin, since the screen already draws a mouth). Build it as shown here for now.',
         img=('sec', '3 Head', dict(crop='hi', hi=['Muzzle'], hi2=['ESP32-S3 CAM board'], arrows=[('Muzzle', (130, -85))],
                                   labels=[('Muzzle', 'muzzle', 'a', 0), ('ESP32-S3 CAM board', 'camera board on its rests', 'a', 0)])),
         need=[('part', 'ESP32-S3 camera board with OV5640 (tested)'), ('part', 'APDS-9960 gesture sensor'), ('part', 'foam tape'), ('screw', 4, 'M2x8')],
         text=['Stand the camera board on the muzzle floor, against its rests, with the camera lens pushed into the square pocket behind the window on the robot\'s right (your left as you face the robot). Its USB-C socket then faces the muzzle port door.',
               'Stand the gesture sensor on its shelf behind the other window, chip centred in the window, and fix it with a small square of foam tape.',
               'Plug the camera board\'s 5 V lead and the gesture sensor lead, feed them through the hole in the head\'s face, then hold the muzzle against the head and drive 4 x M2x8 from inside the head into the muzzle.'],
         check='Look into the muzzle windows from the front: you see the lens in one and the sensor chip in the other, both centred.',
         mistake='Pinching the thin camera ribbon. Fold it gently; a sharp crease breaks it.'),

    dict(id='C6', title='Head onto the collar',
         img=('sec', '3 Head', dict(crop='hi', hi=['Collar', 'Head_Front'], arrows=[('Collar', (-20, -150))],
                                   labels=[('Collar', 'collar (already on the lid)', 'a', 0)])),
         need=[('part', 'the lid with the collar fitted (step B7)'), ('screw', 4, 'M2x8')],
         text=['Feed the head leads that stick out of the collar up through the hole in the head\'s floor.',
               'Sit the head on the collar and drive 4 x M2x8 down through the head floor into the collar, from inside the head.',
               'Connect the leads: 5 V to P1 and the sensor lead to P4 if you have not already, the gesture sensor lead to its row, and the head touch pad wire to the touch board lead.'],
         check='The head sits square and does not wobble. The even gap under the head is meant to be there.',
         mistake='Trapping a lead between the head floor and the collar.'),

    dict(id='C7', title='Speaker into the head back',
         img=('sec', '3 Head', dict(crop='hi', hi=['Head_Back'], hi2=['speaker'], labels=[('speaker', 'speaker in its fences', 'a', 0), ('Head_Back', 'head back', 'a', 0)])),
         need=[('part', '3 W speaker with its 1.25 mm plug')],
         text=['The speaker sits in the fences on the inside of the head back, facing the grille of small holes.',
               'Press it in, plug its lead into the screen board\'s "Speak" port, and put the head back aside. It clips on at the very end (step G4), after the ears are fitted.'],
         check='The speaker cannot rattle in its fences.',
         mistake='Clipping the head back on now. You still need to reach inside the head for the ears.'),
]
