# Desk Buddy guide - assembly steps, part 1: A Body (tub) and B Lid.
# Source: cad/print_v3_1_README.md "Assembly order" and "Screws"; positions from cad/build_print_parts_v3_1.py.
# img kinds:
#   ('sec', section, {hi, hi2, arrows, labels, crop})   real SolidWorks exploded picture, parts outlined
#   ('stl', {parts, cam, labels, hi, arrows, badges})     view made from the STLs (colours from config)
#   ('render', file, crop box or None)                    a SolidWorks picture, cropped
# need: ('screw', count, size) or ('part', text). Text never names a colour: use {{white}} etc.

TUB = ('Torso_Bottom', 'graphite', (0, 0, 0))
LID = ('Torso_Lid', 'white', (0, 0, 0))

STEPS_A = [
    dict(id='A1', title='Get to know the tub',
         img=('stl', dict(parts=[TUB], cam=(18, 52), width=1500, labels=[
             ((42, 18, 60.6), 'hip servo slot (4)', 'r'),
             ((42, 31, 66), 'lead notch (4)', 'r'),
             ((-33.6, 27.8, 27.94), 'servo board standoffs (both walls)', 'a'),
             ((27.5, 24.4, -62), 'USB-C charger ledge', 'r'),
             ((0, 22, -78), 'rear laser wedge', 'r'),
             ((0, 3, 38), 'protection board fences', 'l'),
             ((0, 2.4, 59.7), 'power switch recess', 'l'),
             ((20, 4, 62), 'desk-edge laser incline (3)', 'l'),
             ((0, 22, 78), 'front laser wedge', 'l'),
             ((0, 1, -14), 'battery door opening', 'l'),
         ])),
         need=[('part', 'the tub (Torso_Bottom)')],
         text=['The tub is the robot\'s belly. Almost every electronic part sits in it, so spend two minutes finding each place in the picture before you start. The front of the robot is where the power switch recess is.',
               'Clean the print first: pull off any brim, snip stray strings with the flush cutters, and make sure every slot and window is open.',
               'Pre-thread the screw holes you will use in this chapter. Drive an M2x6 screw into each one and take it out again. The first time is the stiff one, and doing it now, with nothing fitted, means you never have to lean on a finished part.'],
         check='All four hip slots are clean, and a servo slides into each one from outside without forcing.',
         mistake='Driving a screw into an un-threaded hole on a thin wall. Go slowly, straight, and stop as soon as the head touches.'),

    dict(id='A2', title='Hip servos into the tub', fig_mm=150,
         img=('sec', '1 Body', dict(crop='hi', hi2=['hip MG90S'], hi=['Torso_Bottom'], labels=[('hip MG90S', 'hip servo, tabs outside the wall', 'l', 0)])),
         need=[('part', '4 x MG90S 180 degree servo, centred (Bench test, step 5.4)'), ('screw', 8, 'M2x6')],
         text=['Mark each servo lead with a tape flag before you fit it: HFL, HBL, HFR and HBR, for hip front-left, back-left, front-right and back-right. Left and right are always the robot\'s own left and right.',
               'Push each hip servo through its slot in the tub wall from the outside, plug and lead first. The two mounting tabs stay outside, flat against the wall, and the round output boss points outward.',
               'Fix each servo with 2 x M2x6 through its tabs. The screws that came in the servo bag also fit.'],
         check='Each servo\'s tabs sit flat on the wall with no gap, and its output shaft sits in the middle of the round boss hole when you hold a side panel against it.',
         mistake='Trying to fit the servo from inside the tub. The tabs must be outside, so the lead goes in first.'),

    dict(id='A3', title='Servo boards on the side walls', fig_mm=150,
         img=('sec', '1 Body', dict(crop='hi', hi2=['PCA9685 (left)'], hi=['Torso_Bottom'], labels=[('PCA9685 (left)', 'servo board A, left wall', 'r', 0)])),
         need=[('part', '2 x PCA9685 servo board (A0 pad bridged on board B)'), ('screw', 4, 'M2x6')],
         text=['Each servo board stands upright against a side wall, on four printed standoffs. The servo header rows run along the top edge and the green V+ screw terminal sits in the gap at the bottom middle.',
               'Board A goes on the robot\'s left wall. Board B, the one with its A0 pad bridged with solder (Wiring, step 4.6), goes on the right wall.',
               'Screw each board through its two upper holes into the upper standoffs, 2 x M2x6 per board. The two lower standoffs are spacers only: a screwdriver cannot reach them square, so leave them empty.'],
         check='The boards do not rock, and the servo headers face the middle of the tub.',
         mistake='Swapping the boards. If the right board is not the bridged one, both boards answer at the same address and neither works.'),

    dict(id='A4', title='Protection board and fuse',
         img=('stl', dict(parts=[TUB], cam=(12, 62), width=1400, labels=[
             ((0, 3, 38), 'protection board between these fences', 'l'),
             ((0, 12, 38), 'fuse holder taped on top', 'r'),
         ])),
         need=[('part', 'battery pack harness from Wiring step 4.3 (protection board, fuse holder, switch leads)'), ('part', 'foam tape')],
         text=['Lay the protection board flat on the tub floor, between its four fences, near the front. Its wires were soldered on in the Wiring chapter.',
               'Put a strip of foam tape on top of the protection board and stick the fuse holder to it. The 7.5 A fuse stays in.',
               'Lead the three battery wires (black, middle and red) back towards the battery door opening, and the red and black power wires towards the rump, where the charger goes.'],
         check='The board sits flat and nothing metal on it touches a screw tip or another board.',
         mistake='Leaving the cells in the holder while you work. Keep them out until the First power-on chapter.'),

    dict(id='A5', title='USB-C charger at the rump',
         img=('sec', '1 Body', dict(crop='hi', hi2=['USB-C charger'], hi=['Torso_Bottom'], labels=[('USB-C charger', 'charger on its raised ledge', 'r', 0)])),
         need=[('part', 'Type-C 2S charging board (already wired, Wiring step 4.3)'), ('part', 'foam tape')],
         text=['The charger sits on a raised ledge inside the rump wall, above the rear-left hip servo, with its USB-C socket in the opening of the rump wall.',
               'Put a small piece of foam tape on the ledge, slide the board in socket first until the socket face is just behind the opening, and press it down.'],
         check='Plug a USB-C cable in from outside: it goes all the way in without pushing the board back.',
         mistake='Taping the board too far back, so the plug cannot reach the socket once the rump band is on.'),

    dict(id='A6', title='Power switch in the belly',
         img=('stl', dict(parts=[TUB], cam=(14, -52), width=1300, labels=[
             ((0, 0, 59.7), 'power switch, flush in its recess', 'l'),
             ((0, 0, -14), 'battery door opening', 'r'),
         ])),
         need=[('part', 'KCD1 rocker switch (already wired, Wiring step 4.3)')],
         text=['Turn the tub upside down. The power switch clips into the rectangular cut-out at the front of the belly, from outside, turned so the rocker runs front to back.',
               'Feed its two wires in first, then press the switch in until both side clips snap behind the wall. The rocker sits flush in its recess.',
               'Decide now which way is ON and mark it with a tiny dot of paint or a sticker. The switch is the only way to turn the robot off quickly.'],
         check='The switch does not move when you press the rocker hard in both directions.',
         mistake='Soldering the switch wires after it is clipped in. Solder first (Wiring chapter), then clip it in.'),

    dict(id='A7', title='Five laser sensors in the tub',
         img=('stl', dict(parts=[TUB], cam=(18, 52), width=1500, labels=[
             ((0, 22, 78), 'front obstacle laser (chest)', 'l'),
             ((20, 4, 62), 'desk-edge, front-left', 'r'),
             ((-20, 4, 62), 'desk-edge, front-right', 'l'),
             ((0, 22, -78), 'rear obstacle laser (rump)', 'r'),
             ((0, 4, -62), 'desk-edge, rear', 'r'),
         ])),
         need=[('part', '5 x VL53L0X laser sensor, tested (Bench test)'), ('part', 'foam tape')],
         text=['Five of the seven laser sensors live in the tub. Two look forward and backward for obstacles, through the chest and rump windows. Three look down at the desk to stop the robot before an edge: two at the front, either side of the power switch, and one at the rear.',
               'Peel the protective film off each sensor chip. Stick each board to its incline or wedge with a small square of foam tape, chip facing the window, and centre the chip on the hole.',
               'Flag each sensor lead with its name. Their XSHUT wires go to servo board B, channels 9 to 13 (Wiring, laser table).'],
         check='Look through each window from outside: you can see the small black chip in the middle of the hole.',
         mistake='Leaving the clear film on the chip. The sensor then reads a short, wrong distance all the time.'),

    dict(id='A8', title='Battery holder onto the battery door',
         img=('stl', dict(parts=[('Battery_Door', 'graphite', (0, 0, 0)), ('Battery_Clamp', 'graphite', (0, 22, 0))],
                          cam=(16, 50), width=1300, hi=['Battery_Clamp'],
                          arrows=[((0, 30, -35), (0, 23, -35))],
                          labels=[((0, 22, -35), 'clamp: 2 x M2x8', 'r'), ((0, 4, -10), 'holder between these fences', 'l')])),
         need=[('part', '2 x 18650 holder (wired, cells OUT)'), ('part', 'battery door and clamp'), ('screw', 2, 'M2x8')],
         text=['Lay the empty cell holder between the fences on the inside of the battery door. Its wires point to the front.',
               'Put the clamp bar across the holder and screw it to the two posts, 1 x M2x8 each. Tighten until the holder cannot slide, no further.',
               'Do not fit the door to the tub yet. The cells go in, and the door goes on, in the First power-on chapter.'],
         check='The holder does not move when you shake the door.',
         mistake='Over-tightening the clamp and bending the holder, which then loosens the cell contacts.'),

    dict(id='A9', title='Side panels on',
         img=('sec', '1 Body', dict(hi=['Side_Panel_Left', 'Side_Panel_Right'], arrows=[('Side_Panel_Left', (-130, -75)), ('Side_Panel_Right', (130, 75))],
                                   labels=[('Side_Panel_Left', 'left side panel', 'r', 0), ('Side_Panel_Right', 'right side panel', 'l', 0)])),
         need=[('part', 'left and right side panels (no screws)')],
         text=['Each side panel covers the two hip servos on its side. It has four snap hooks and no screws.',
               'Hold the panel so its two round holes line up with the round bosses of the hip servos, then press it straight onto the wall until all four hooks click. Do the left panel on the left, the right panel on the right: the slot for the leg leads is at the top of each round hole.',
               'Fit the side panels before the legs, because the thigh cups help hold the panels in place.'],
         check='The panel sits flush all round, and each servo boss is centred in its round hole.',
         mistake='Pressing on one end only. Press both ends together, or a hook can break off.'),
]

STEPS_B = [
    dict(id='B1', title='Get to know the lid (underside)',
         img=('stl', dict(parts=[LID], cam=(198, -55), width=1500, labels=[
             ((0, 46, 14.8), 'motion sensor fence', 'l'),
             ((0, 46, -28.5), 'hub fences', 'l'),
             ((-29.4, 44, -20), 'cable-tie anchors', 'l'),
             ((5, 34, -62), 'tail servo ribs', 'l'),
             ((23.2, 46, 31.7), 'touch board fence', 'r'),
             ((35, 40, 0), 'side laser shelf (2)', 'r'),
             ((30, 47.6, -25), 'touch pad screw (4)', 'r'),
             ((15, 47.6, 60), 'collar screws from inside (4)', 'r'),
         ])),
         need=[('part', 'the lid (Torso_Lid)')],
         text=['The lid carries the motion sensor, the touch board, the power hub, the tail servo, the two side lasers and four touch pads. Turn it upside down and find each place.',
               'Clean the print and pre-thread the holes you will use in this chapter: the tail servo pilots, the four touch pad pilots and the four collar holes.'],
         check='The lid\'s top edge is smooth. If the first millimetre drooped while printing, sand it lightly (Printing, note A).',
         mistake='Pre-threading the touch pad holes with an M2x6. It is too long and comes out through the top. Use an M2x4.'),

    dict(id='B2', title='Motion sensor and touch board',
         img=('sec', '2 Lid', dict(crop='hi', hi2=['MPU6050', 'MPR121'], hi=['Torso_Lid'], labels=[('MPU6050', 'motion sensor (MPU6050)', 'l', 0), ('MPR121', 'touch board (MPR121)', 'l', 0)])),
         need=[('part', 'MPU6050 motion sensor'), ('part', 'MPR121 touch board'), ('part', 'foam tape')],
         text=['Both boards sit in their own fences on the underside of the lid, components facing down.',
               'Stick each one in with foam tape. The motion sensor must sit flat and square in its fence, because the robot uses it to know which way is up.'],
         check='Neither board can rock. The motion sensor\'s edges are parallel to the fence.',
         mistake='Mounting the motion sensor at an angle. It then thinks the robot is always leaning.'),

    dict(id='B3', title='Power hub under the lid',
         img=('sec', '2 Lid', dict(crop='hi', hi2=['perfboard hub'], hi=['Torso_Lid'], labels=[('perfboard hub', 'power and sensor hub (2 x Mini560)', 'r', 0)])),
         need=[('part', 'the hub you built in Wiring step 4.5'), ('part', '2 cable ties')],
         text=['The hub carries the two 5 V power modules, the two big capacitors and the small resistors. It fits in the large fence towards the back of the lid.',
               'Press it in, components facing down, and pass one cable tie under each pair of anchors beside the fence. Pull them snug, not tight, and snip the tails.'],
         check='The hub does not move, and no capacitor leg touches the lid\'s screw bosses.',
         mistake='Standing the capacitors upright. Lay them on their side; there is only 13 mm of room.'),

    dict(id='B4', title='Two side lasers',
         img=('sec', '2 Lid', dict(crop='hi', hi2=['side VL53L0X'], hi=['Torso_Lid'], labels=[('side VL53L0X', 'side laser on its shelf', 'r', 0)])),
         need=[('part', '2 x VL53L0X laser sensor'), ('part', 'foam tape')],
         text=['One laser stands on a shelf against each side wall of the lid, looking sideways through the small window.',
               'Peel the film off the chip, slide the board down behind the lip on its two posts, chip facing the window, and fix it with a small square of foam tape.'],
         check='From outside you can see the chip through the window.',
         mistake='Fitting the board chip-inward. The chip must face the window.'),

    dict(id='B5', title='Tail servo',
         img=('sec', '2 Lid', dict(crop='hi', hi2=['tail MG90S'], hi=['Torso_Lid'], labels=[('tail MG90S', 'tail servo under its ribs', 'r', 0)])),
         need=[('part', 'MG90S servo, centred, lead flagged TAIL'), ('screw', 2, 'M2x6')],
         text=['The tail servo hangs under two ribs near the back of the lid, with its output shaft pointing up into the round tail socket.',
               'Hold the servo under the ribs with its tabs against them and drive 2 x M2x6 up through the tabs from inside the lid.'],
         check='Look at the lid from the top: the servo spline sits in the middle of the tail socket.',
         mistake='Fitting the servo with its shaft at the wrong end. The shaft must be under the socket, not under the lid.'),

    dict(id='B6', title='Four foil touch pads',
         img=('stl', dict(parts=[LID], cam=(198, -55), width=1400, labels=[
             ((30, 47.6, -25), 'pad E0, back-left', 'a'), ((-30, 47.6, -25), 'pad E1, back-right', 'a'),
             ((28, 47.6, -60), 'pad E2, rump-left', 'a'), ((-28, 47.6, -60), 'pad E3, rump-right', 'a'),
         ])),
         need=[('part', 'kitchen foil, 4 pieces about 25 x 20 mm'), ('part', '4 grey wires from the touch board'), ('screw', 4, 'M2x4')],
         text=['The robot feels petting through four foil pads on the inside of the lid, under the four raised ovals on top.',
               'Cut a foil piece with a small tab, poke a hole in the tab, and lay it on the inside of the lid under an oval. Strip 5 mm of its wire, wrap the bare end once round an M2x4 screw, and drive the screw through the foil tab into the pad hole so the wire and foil are clamped together.',
               'A dot of superglue at each corner keeps the foil flat. Wire E0 to E3 as the labels show.'],
         check='With the multimeter on beeper mode, each wire beeps to its foil.',
         mistake='Using an M2x6 here. It comes out through the top of the lid.'),

    dict(id='B7', title='Collar onto the lid',
         img=('stl', dict(parts=[LID, ('Collar', 'graphite', (0, 25, 0))], cam=(22, 45), width=1400, hi=['Collar'],
                          arrows=[((30, 82, 58), (30, 66, 58))],
                          labels=[((0, 75, 58), 'collar', 'l'), ((15, 50, 60), '4 x M2x8 from inside the lid', 'r')])),
         need=[('part', 'collar'), ('screw', 4, 'M2x8')],
         text=['Before you fit the collar, feed the head\'s leads up from the hub through the lid\'s neck opening: the screen power lead, the screen sensor lead (port P4), the camera power lead, the gesture sensor lead and the head touch pad wire. Leave about 15 cm sticking out.',
               'Set the collar on the lid, leads through its middle, and screw it on from inside the lid with 4 x M2x8.'],
         check='The collar sits flat all round, and every head lead comes out of its top.',
         mistake='Fitting the collar first and then trying to push plugs through it. Feed the leads first.'),
]
